### ISSUE TITLE
[GBA] Super Robot Wars J audio issues.

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#1092]
The sound seems slightly off in SRWJ as a whole compared to the console.

Not sure if this is a factor, but I'm using the fan translation in the libretro build.

**Comment by JMC47** [comment]
Can you give any further details?  Comparisons to a track where it's very noticeable?  Anything at all?

**Comment by EmoNewtype** [comment]
This issue is also present in standalone Windows desktop versions 0.6.3 and 0.7 beta and is consistent across both English and Japanese versions. Certain instruments are out of tune, and make metallic screeching sounds during some songs. This is very noticeable in the tracks used when selecting a character for a new game, and when loading a save file, though present in most songs. The issue seems to affect more than one audio channel, though which channels are affected seems dependent on song. Super Robot Wars D and R have a similar issue, and due to running on the same engine, SRW A likely does as well.

**Comment by EmoNewtype** [comment]
After some more testing, the audio distortion seems to be in the FIFO A and FIFO B channels specifically.

**Comment by EmoNewtype** [comment]
Currently using Windows Desktop 0.8 beta 1. Opening the log and selecting game errors causes messages similar to "[GAME ERROR] GBA Memory:	Misaligned DMA source address: 0x081ECE36" to appear en masse whenever distorted audio plays, though the value of the source address changes depending on what notes are being played. This affects the Super Robot Wars games mentioned in my previous post as well, and the message does not appear when playing games without audio distortion. Hopefully this information is helpful.

**Comment by endrift** [comment]
I believe this is fixed now, I'm not sure.
