### ISSUE TITLE
Game overrides (Tilt, Gyroscope, Light, Rumble) not changable/mappable

### ISSUE THREAD

**Issue by ROMaster2** [mgba-emu/mgba#11]
Light can be changed manually through Game Pak Sensors but cannot be mapped in any which way, whether to toggle an increase/decrease or fix amount.

Tilt, Gyroscope, and Rumble cannot be mapped or even modified what-so-ever. There does not appear to be any settings to change those values.

**Comment by endrift** [comment]
The lack of a mapping for the solar levels is a bug that crept in in the very last commit of 0.2.0. It will be fixed in 0.2.1, and is already fixed in the nightlies. I just added a way to make keyboard shortcuts to specific light levels, on top of that.

Tilt and gyro do not have controls at the moment due a lack of planning. I haven't figured out a good way to expose gyro especially without using an actual gyroscope to do it. I may make tilt mappable to analog sticks, but I'm not sure. It will take some testing.

Rumble is a game output, not input, so there's nothing to be modified. Support for making controllers rumble was added very recently, and should be in the nightlies by now.

**Comment by endrift** [comment]
This is mentioned in [the mGBA support FAQs](https://forums.mgba.io/showthread.php?tid=6), but obviously I want to make it so that it just works out of the box as best as possible.

**Comment by endrift** [comment]
Tilt and rumble are now exposed, although not configurable. Gyro will probably be tougher, though.

**Comment by endrift** [comment]
Gyro is exposed (rotation of the analog stick), but not configurable. Configuration will be done soon.

**Comment by endrift** [comment]
All fixed as of 6248e44e47a8156555f5b9873a24093643a8a12f, which will be present in the upcoming nightly (in roughly 19 hours).

**Comment by saulfabregwiivc** [comment]
Hello there @endrift, how i can configure the standalone Wii port of mGBA Wii for emulate GBA tilt sensor games (WarioWare: Twisted!, Yoshi Topsy-Turvy, etc.) using a Wiimote (without Wii MotionPlus nor Wii Remote Plus, because i don't have one)?

Because i have tried playing WarioWare Twisted in latest development build of mGBA Wii but when i was tilting the Wiimote it didn't tilt anything. Any help for configure that?

**Comment by endrift** [comment]
Yoshi uses an accelerometer thus is supported without a Wii Motion Plus, but WarioWare uses a gyroscope, which is what the Wii Motion Plus is. Without a gyroscope, interpolated accelerometer controls would be super clunky at best. I tried to implement this at one point but it didn't work.

**Comment by saulfabregwiivc** [comment]
F for WarioWare Twisted not playable with normal Wiimote without Wii MotionPlus...

But could you try to write code for emulate the gyroscope by using Wiimote only (without Wii MotionPlus or Wii Remote Plus)?

Like VBA GX has support for it. In VBA GX i can play WarioWare Twisted using the normal Wiimote (without any Wii MotionPlus) but the speed bothers me a bit.
Could you check its code for try to implement it to mGBA Wii so i can play WW Twisted at a reasonable speed?

**Comment by endrift** [comment]
I said I already tried that. I couldn't get it working well.

**Comment by saulfabregwiivc** [comment]
oh ok thanks :(
So i will have to try to borrow somebody's Wii MotionPlus or Wii Remote Plus and play it on mGBA :P 
A question... does the Wii MotionPlus accessory (not built-in) support on mGBA Wii? For test it with WarioWare Twisted :)

**Comment by endrift** [comment]
I haven't tried it but it should.
