### ISSUE TITLE
Yu-Gi-Oh! The Sacred Cards - black line whenever there's a screen transition

### ISSUE THREAD

**Issue by SuperrSonic** [mgba-emu/mgba#1118]
![yu-gi-oh the sacred cards ss1](https://user-images.githubusercontent.com/6880539/42126973-a37c596c-7c5e-11e8-91c6-a26c2f735e47.png)

It seems to not reproduce on the Windows builds, but happens on Wii and 3DS builds, tested using EUR rom, bios on/off.

Broke in: 7fd3eb722bc6fd993f1df4c9e81c16f3c101f245
Still worked: 7cb30ba83e0805cba80ee6ccca8fe9c1bdc61b39

**Comment by JMC47** [comment]
Can confirm it does not happen on Windows, I still need to test if it happens on 3DS/Wii.  Oddly enough, I do see a "vsync" line there on Windows, but that disappears when doing frame-by-frame, so that's likely not an issue.

![image](https://user-images.githubusercontent.com/6598209/45122438-d0d60180-b131-11e8-96f1-e45325b8db1e.png)

**Comment by endrift** [comment]
I can reproduce.
