### ISSUE TITLE
mGBA-build-2018-09-02-win32-5211 random crash.

### ISSUE THREAD

**Issue by Cibomatto2002** [mgba-emu/mgba#1158]
Like the title says I have uploaded a .DMP dump file.

http://www.filedropper.com/mgba_1

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Pentium G3240 @ 3.10GHz
	Haswell 22nm Technology
RAM
	8.00GB Dual-Channel DDR3 @ 698MHz (10-10-10-25)
Motherboard
	Gigabyte Technology Co. Ltd. H81-D3 (SOCKET 0)	28 °C
Graphics
	ELEFW328 (1360x768@60Hz)
	Intel HD Graphics (Gigabyte)
	1023MB NVIDIA GeForce GT 720 (EVGA)	47 °C
	ForceWare version: 365.10
	SLI Disabled

**Comment by endrift** [comment]
What the heck is a dmp file?

Please actually describe the circumstances under which crashes occur.

**Comment by Cibomatto2002** [comment]
It's a small memory dump file that is created by Windows if a crash occurs. Here is a link to read about it.
https://support.microsoft.com/en-us/help/315263/how-to-read-the-small-memory-dump-file-that-is-created-by-windows-if-a

Here is a video of what i'm talking about. 

https://www.youtube.com/watch?v=fcEVkkFbOK4&feature=youtu.be

**Comment by Raijinili** [comment]
I am also experiencing crashes on the same build. Windows 10, Intel graphics. I have tried two GBC games and a GBA game.

The game runs for up to a few minutes and crashes. The crashes do not seem to be tied to any particular in-game event. One crash for Chain of Memories happened at ~1:15, while another happened within 15 seconds of starting the emulation, and a third run crashed at 3:10. I didn't press any buttons during the tests.

I suspect that out-of-bounds or uninitialized memory is being read, and that's why the crashes are unpredictable.

**Comment by endrift** [comment]
Do you have rewind enabled? Can you bisect when this started?

**Comment by Raijinili** [comment]
Rewind for what? mGBA, Visual Studio, or the git repo? I turned on Rewind in the emulator just now, but since the emulator still crashes, I don't know how it'd help.

---

I did a few more tests (still on the same build) with Fast Forward. The crashes seem to happen sooner, so it is during the course of emulation (and this speeds up testing). One could count the number of times the theme song loops to estimate the timing.

Switching sound to Qt and loading the game causes the emulator to infloop (taking up 100% of two cores) instead of crash. That's probably a different bug.

Switching video from OpenGL to Qt or OpenGL 1.1 still has random crashes.

---

On: mGBA-0.6.3-win32 (April)

No crash. Oddly, the first few times I opened it, it simply opened and closed without even popping up a window. I then tried to run it through a Command Prompt window, while watching Task Manager for `mgba.exe` to pop up and disappear. Instead, it ran normally.

When I loaded the game, it crashed instantly. I then reopened it and loaded it, and it ran fine for several loops.

---

On: mGBA-build-2018-09-15-win32-5240-9de8f084ba55460b02d300c1dd8b8e6c56f691d5

Still crashes, with the same non-pattern.

---

Bisecting manually, because I don't know any better. 5201 doesn't crash. 5202 does.

Method: I opened one build, loaded a game, put it on Fast Forward, did it again for a second concurrent instance, bisected upward, and closed it when I finished installing the next game or started worrying for my CPU. I repeated until a build crashed, then tested the boundary of builds with several instances to make sure that one build crashes and the one before it doesn't.

**Comment by endrift** [comment]
Might be fixed in b86d3f9fc3fe60ab362ed824b5b16e61608b10ff. Please retest.

**Comment by Raijinili** [comment]
Do you mean the Qt sound crash? That's a separate crash than this issue. Should I open another issue?

**Comment by endrift** [comment]
That change doesn't affect Qt sound. So, no, it won't fix that. Please do file a bug on the sound hang though.

**Comment by Raijinili** [comment]
Build 5243 (the revision before) still crashes, but 5244 (b86d3f9) does not.

However, the width is wrong in the new build.
![image](https://user-images.githubusercontent.com/2422807/45591275-f4602f80-b91b-11e8-8c80-cff502cb5661.png)

---

Qt sound issue here: #1173

**Comment by endrift** [comment]
I swear I tested that but I had the same problem when I loaded the game. Fixed now. Sorry about that.

**Comment by Raijinili** [comment]
No crash on build 5246. I confirmed that old builds still crash, so the fix worked.

**Comment by Raijinili** [comment]
I forgot this wasn't my issue. @Cibomatto2002 I think the next step is for you to also confirm that the new build fixes the crash for you.

**Comment by Cibomatto2002** [comment]
No problems so far.
