### ISSUE TITLE
Misspelling (French)

### ISSUE THREAD

**Issue by Sewef** [mgba-emu/mgba#1374]
![image](https://user-images.githubusercontent.com/27089398/55688825-9198b900-597d-11e9-891a-5a49fb7c19ee.png)

Audio/Vidéo → Enregistrer le GIF...
Should be "Enregistrer un GIF..."

Chsoiir un fichier
Should be "Choisir un fichier"

**Comment by RunisDauphin** [comment]
We have found several other mistranslations:

Lines "File -> Load Alternate Save", "File -> Load state file", "File -> Save state file" are not translated:
![Fichier](https://user-images.githubusercontent.com/49384468/55700860-3bedfc00-59d1-11e9-9b98-b8f0b061bc15.png)
Suggested "Charger sauvegarde alternative", "Charger fichier de sauvegarde", "Sauver fichier de sauvegarde".
Lines "Emulation -> Yank game pak", "Emulation -> Step backwards", "Emulation -> Synchro  vidéo" are not translated:
![Émulation](https://user-images.githubusercontent.com/49384468/55700917-7eafd400-59d1-11e9-8deb-362da57be8d6.png)
Suggested "Extraire game pak", "Pas en arrière", "Synchro vidéo".
Lines "Audio/Video -> Adjust layer placement" is not translated and line "Enregistrer l'enregsitrement vidéo" (Register video log in English) is incorrectly written:
![Audio-Vidéo](https://user-images.githubusercontent.com/49384468/55700970-c0407f00-59d1-11e9-997f-66a6b15398cd.png)
Suggested "Ajuster disposition de couche" and correction should be "Enregistrer l'enregistrement vidéo".
All these lines present in "Tools -> Parameters -> Hotkeys" should be corrected as well.

Now onto "Tools -> Parameters":
In Audio/Video, it says "imaes par secondes" instead of "images par seconde", and "Filtrage bilinèaire" instead of "Filtrage bilinéaire".
![Paramètres - Audio-Vidéo](https://user-images.githubusercontent.com/49384468/55701175-74daa080-59d2-11e9-9baf-870a345aeb40.png)
In Interface, it says "Afficher quand aucun jeu est ouvert", but I am pretty sure the line should be "Afficher quand aucun jeu n'est ouvert".
![Paramètres - Interface](https://user-images.githubusercontent.com/49384468/55701192-88860700-59d2-11e9-8600-e9d732cf3849.png)
In Emulation, it says "supplèm." as an abreviation of "supplémentaire". I think the abreviation should be "supplém.".
![Paramètres - Émulation](https://user-images.githubusercontent.com/49384468/55701215-9e93c780-59d2-11e9-85c3-8dabe97e299a.png)
In Paths, it says "Etat" and "Ecran" instead of "État" and "Écran".
![Paramètres - Chemins](https://user-images.githubusercontent.com/49384468/55701229-b1a69780-59d2-11e9-861f-59977e5300bb.png)
In Game Boy, lines "Super Game Boy model" and "Game Boy Color model" are not translated. Suggested "Modèle Super Game Boy" and "Modèle Game Boy Color".
![Paramètres - Game Boy](https://user-images.githubusercontent.com/49384468/55701246-c3883a80-59d2-11e9-9089-c73fdaa87c6a.png)
In Hotkeys, lines "Undo loading savestate" and "Undo saving savestate" are partially not translated. Suggested "Défaire le chargement d'état" and "Défaire la sauvegarde d'état".
![Paramètres - Raccourcis - Undo Loading](https://user-images.githubusercontent.com/49384468/55701279-dbf85500-59d2-11e9-8c8e-9234e033812c.png)
![Paramètres - Raccourcis - Undo Saving](https://user-images.githubusercontent.com/49384468/55701280-def34580-59d2-11e9-913d-12129b360de7.png)
In Hotkeys, line "Autofire LL" is not translated (and I have no idea why the button is called "LL", bearing in mind that, in English, line is called "Autofire L"). Line should be "Tir Auto L".
![Paramètres - Raccourcis - Tir Auto](https://user-images.githubusercontent.com/49384468/55701314-fa5e5080-59d2-11e9-9889-3a601de95c2c.png)
In Shaders, line "Sahder actif" should be "Shader actif".
![Paramètres - Shaders](https://user-images.githubusercontent.com/49384468/55701343-119d3e00-59d3-11e9-93ef-7a617e2dcf82.png)

Thanks for hearing us. Maybe there are more translation errors we have not found yet.

**Comment by BenjaminSiskoo** [comment]
Thanks I'll check that thiis week or next week

**Comment by RunisDauphin** [comment]
You're welcome. If we find anything else, we will tell you.

**Comment by BenjaminSiskoo** [comment]
Great, If I forget send me a reminder :)

**Comment by RunisDauphin** [comment]
This is just a reminder about the translation thing.

When do you think it would be finished? I am just asking to pick that version once that is done.

**Comment by BenjaminSiskoo** [comment]
Thanks guys, Merci les gars

I'm also fixed some typos by my side.

**Comment by RunisDauphin** [comment]
Much welcome.

Is any version with this corrected ready to be released? Because r5566 was released like a week ago and, evidently, has not any of those corrections onto it.

**Comment by BenjaminSiskoo** [comment]
Need to wait to next release, I'm just a translater, I'm not a part of this project :)

**Comment by endrift** [comment]
Fixes are merged and should be available in r5570 once that's online.

**Comment by BenjaminSiskoo** [comment]
Thanks @endrift :)

**Comment by RunisDauphin** [comment]
First off, thanks for your hard work and for these corrections.
I have version r5571 (a32cb5cc = 2737616332) and I found that some errors still made their way into the version:

-/Lines "File -> Load state file", "File -> Save state file", are not translated into French.
![Fichier](https://user-images.githubusercontent.com/49384468/56558732-f1a77600-659f-11e9-98c4-24e992754a07.png)
  Suitable translation: Charger fichier de sauvegarde, Sauver fichier de sauvegarde.
  Also replace in "Tools -> Parameters -> Hotkeys" these untranslated lines for the translated ones.

-/In "Tools -> Parameters -> Audio/Video", in French, it says "images par secondes" instead of "images par seconde", and "Filtrage bilinèaire" instead of "Filtrage bilinéaire".
![Outils - Audio-Vidéo](https://user-images.githubusercontent.com/49384468/56558758-02f08280-65a0-11e9-95ae-922dcbda5f38.png)

-/In "Tools -> Parameters -> Paths", in French, it says "Etat" and "Ecran" instead of "État" and "Écran".
 I think I can look pass through these ones, because no capital letter has accents.
![Outils - Chemins](https://user-images.githubusercontent.com/49384468/56558796-1e5b8d80-65a0-11e9-9503-8839d598e1a0.png)

-/In "Tools -> Parameters -> Game Boy", in French, lines "Game Boy model", "Super Game Boy model" and "Game Boy Color model" are not translated. Suggested "Modèle Game Boy", "Modèle Super Game Boy" and "Modèle Game Boy Color".
![Outils - Game Boy](https://user-images.githubusercontent.com/49384468/56558810-2c111300-65a0-11e9-8118-be9e7dcc240d.png)
In fact, Game Boy Model WAS translated up to r5566.

I only checked the places where these translation errors were, just to see the results, maybe there are still more errors that we have not found. I think it was an error to close this thread, just in case something went wrong.

Again, thanks for your attention and your work, M. Pfau and Siskoo.

**Comment by BenjaminSiskoo** [comment]
Hello, 

Happy to improve the french translation :)

I can't find these strings : -/Lines "File -> Load state file", "File -> Save state file", are not translated into French.
Same for this : Also replace in "Tools -> Parameters -> Hotkeys" these untranslated lines for the translated ones.

-/In "Tools -> Parameters -> Paths", in French, it says "Etat" and "Ecran" instead of "État" and "Écran".
I think I can look pass through these ones, because no capital letter has accents.
With uppercase, don't need that.

-/In "Tools -> Parameters -> Game Boy", in French, lines "Game Boy model", "Super Game Boy model" and "Game Boy Color model" are not translated. Suggested "Modèle Game Boy", "Modèle Super Game Boy" and "Modèle Game Boy Color".

done, it seems there is a problem with the french file 
    <message>
        <location filename="../SettingsView.ui" line="1180"/>
        <source>Game Boy model</source>
        <translation type="unfinished">Modèle de GameBoy</translation>

**Comment by RunisDauphin** [comment]
Sorry for the mistake I made with that anotation. I will be eagerly waiting for that new release with these improvements. Working hard for having a high quality French translation, as well as the older ones had (the Spanish translation had a very good quality when I used it up to v0.6.3).

Huge thanks to the team.

Merci beaucoup, M. Siskoo, and M. Pfau when the new release is out.

**Comment by BenjaminSiskoo** [comment]
Pas de soucis, c'est agréable d'avoir des retours constructifs :)

**Comment by RunisDauphin** [comment]
Je sais que ce commentaire est hors sujet, mais je ne savais pas que vous travailliez (et travaillez) dans la traduction d'autres émulateurs au français à tradu-france. Vous êtes très habile dans cette matière et j'ai des quelques versions traduites de quelques émulateurs.

Je ne sais pas pas comment vous remercier ce sublime travail (à part de les télécharger et les utiliser).

Je voudrais poursuivre un chemin similaire au sujet des jeux vidéo, mais maintenant il semble être très difficile.

Continuez avec ce travail: c'est magnifique.

**Comment by BenjaminSiskoo** [comment]
C'est un message très agréable à lire. On peut laisser les vouvoiements et on peut en parler en mp (il y a mon email sur mon site). On pourra voir les projets de jeux vidéo (si c'est de la traduction de roms par ex).

Merci pour ces compliments :)

**Comment by RunisDauphin** [comment]
D'accord. Je crois qu'on devrait continuer cette conversation par privé au
lieu de par github, et laisser la conversation à github pour mGBA et des
choses similaires. Pour finir, j'ai vu que vous avez mis disponible la
version 1.60 de SNES9X: merci, je l'ai déjà téléchargé.

Runis Dauphin

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by BenjaminSiskoo** [comment]
siskoo @ tradu-france.com voici mon mail

**Comment by endrift** [comment]
@BenjaminSiskoo what's the status of this?

**Comment by BenjaminSiskoo** [comment]
@endrift no more news from Sewef I guess you can close thanks :)

**Comment by endrift** [comment]
Were there no changes to merge? I don't know French so I have no idea what you were conversing about.

**Comment by BenjaminSiskoo** [comment]
I just gave my email to Sewef and no more news since the last time.  It seems his posts have not displayed. I don't know why. So you can close this bug report :) I will check the french translation this we or later :)
