### ISSUE TITLE
(Toolchain bug?) Failing to build on msys2/mingw-w64

### ISSUE THREAD

**Issue by lotharsm** [mgba-emu/mgba#1415]
Hi there,

currently, compiling mGBA via MSYS2/Mingw-w64 seems to be broken:
```

-- Checking for one of the modules 'sdl2'
CMake Error at C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:15 (message):
  The imported target "Qt5::Gui" references the file

     "C:/building/msys32/mingw64/x86_64-w64-mingw32/lib/libglu32.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:45 (_qt5_Gui_check_file_exists)
  C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:70 (_qt5gui_find_extra_libs)
  C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:212 (include)
  C:/msys64/mingw64/lib/cmake/Qt5Multimedia/Qt5MultimediaConfig.cmake:105 (find_package)
  src/platform/qt/CMakeLists.txt:25 (find_package)
```

For the record, my entire build environment is stored in c:\msys64. I have no clue where the folder/reference c:\building originates from.

Is it possible that this is an issue with mGBA or is it an issue with the build toolchain/MSYS2 itself? I'm a bit lost at this issue.

**Comment by endrift** [comment]
This appears to be https://github.com/msys2/MINGW-packages/issues/5253.

**Comment by Margen67** [comment]
I at least got the SDL build to work by replacing all instances of the invalid path (`C:/building/msys32/`) in `C:/msys64/mingw64/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake` with the right one (in my case the default one) `C:/msys64/`
That gets it to build, but after running `cpack -G ZIP` this happens:
`Warning: Unable to read E:\mingwbuild\mingw-w64-qt5\pkg\mingw-w64-x86_64-qt5\mingw64\share\qt5\mkspecs\qconfig.pri: The system cannot find the path specified.
Unable to find dependent libraries of E:\mingwbuild\mingw-w64-qt5\pkg\mingw-w64-x86_64-qt5\mingw64\bin\Qt5Core.dll :Cannot open 'E:/mingwbuild/mingw-w64-qt5/pkg/mingw-w64-x86_64-qt5/mingw64/bin/Qt5Core.dll': The system cannot find the path specified.`

Attempting to open mGBA (qt) from the cpack packages folder results in these errors:
`This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`
`A fail fast exception occurred. Exception handlers will not be invoked and the process will be terminated immediately. `
The SDL build works, though.

**Comment by endrift** [comment]
I don't believe CPack runs the deploy script that gathers the plugins. The regular distribution build is statically linked so you don't need to do that. However, managing a static version of Qt is kind of difficult.
