### ISSUE TITLE
WiiU GamePad Support

### ISSUE THREAD

**Issue by xXS4ALLx** [mgba-emu/mgba#1423]
Will there ever be support for the WiiU GamePad?

All of the other known emulators such as:

FCE Ultra GX
Genesis Plus GX
Snes9x GX
Visual Boy Advance GX
Wii64
WiiSX

All support the GamePad.

Why do we need this?
There is a few of us that want to create/inject a WiiU Forwarder to launch mGBA, and play on the WiiU's GamePad, at the moment, if you inject, the GamePad only acts as a screen but you still require Wii Remote to play.

I did a search through the open and closed issues and couldn't find any posted issues regarding this.

**Comment by olo85** [comment]
@xXS4ALLx Hi there, I was following one of your discussion dated back to 2017 I guess, and I wanna ask you, have you managed to fix the issue with Nintendont+Virtua_Striker_4_Triforce+Wii U Gamepad? Just curious since I am struggling and totally unable yet to multiplay an amazing game made for multiplay.

**Comment by xXS4ALLx** [comment]
@olo85, nope still no fix for VS4 Triforce, as you know, no reply for that issue, I don't think there is anything we can do to fix, it's either Nintendont or the way the game handles the controls, but I think Nintendont should be looked at first but again no reply from the dev.

**Comment by olo85** [comment]
@xXS4ALLx Thank you for your reply. Well no good news then. The problem is that the Gamepad is always recognised as player one or two, no matter what I do. What if we get to bypass it by using two Wii U Pro controller via bluetooth to multiplay? Do you think is possible. I just do not have any Wii U pro controller as of now, before purchasing them would be nice to know if someone already tried.

**Comment by endrift** [comment]
Gonna need to set up HBC on my vWii to implement this but it looks not bad to implement.

**Comment by endrift** [comment]
So I have my Wii U homebrewed and everything now, but the vWii doesn't let the gamepad be used at all. It seems you need some sort of forwarder and I'm not sure how to set those up. GBATemp, as it often does, has scattered and bad instructions with no centralized thread. There isn't info elsewhere that I've found either.

**Comment by endrift** [comment]
Added in 0d96ba4f8fab5af32ea2491c7ecc8d958cdf50de.
