### ISSUE TITLE
Sprites to not render with OpenGL video renderer

### ISSUE THREAD

**Issue by ROMaster2** [mgba-emu/mgba#1434]
Happened with the latest build, `0.8-5800-a1cdd65e`. Might be related to #1419, not sure.

With all other settings default (besides controller bindings), when the `Video renderer` under `Enhancements` is set to `OpenGL`, sprites do not load in games. This happens even when the `High-resolution scale` is kept at x1.

Could this some how be related to my PC specifically? I don't see others having the same issue.

Video example: https://www.youtube.com/watch?v=oaGmKLcC1lU

**Comment by endrift** [comment]
What GPU do you have?

**Comment by ROMaster2** [comment]
```
Manufacturer               NVIDIA
Model                      GeForce GTX 1070
Revision                   A2
Subvendor                  NVIDIA (10DE)
Current Performance Level  Level 0
Current GPU Clock          1506 MHz
Current Memory Clock       4006 MHz
Current Shader Clock       4006 MHz
Technology                 16 nm
Bus Interface              PCI Express x16
Temperature                51 °C
Driver version             24.21.13.9826
BIOS Version               86.04.50.40.e3
Memory                     4095 MB
```

**Comment by angrylion7** [comment]
I'm experiencing the same issue, on Windows 7 x64 with GeForce GT630 (GK208). It started to happen maybe a couple dozen commits before `0.8-5800-a1cdd65e`, or something of that order. Sprites worked fine before that. I didn't report it because I use a relatively old nVidia driver (355.98) and planned to re-check on an updated driver. I also saw you actively working on OpenGL and was hoping to see it fixed soonish.

**Comment by endrift** [comment]
I can't reproduce this on Windows 10 with a GTX 2080. Does this happen with latest drivers? @ROMaster2 what OS are you on? @angrylion7 can you try to track down when it started failing?

**Comment by angrylion7** [comment]
@endrift Sprites were broken by this commit: [https://github.com/mgba-emu/mgba/commit/b2450bac5e881de3ba64cf3c9718793ce6ef9873](url)
Haven't checked with the latest drivers yet.

**Comment by angrylion7** [comment]
OK, upgrading to the latest nVidia driver v430.86 fixed this for me. Sorry for the trouble. @ROMaster2 might be experiencing the same thing, because the driver version string that he posted looks like it's older than mine with this driver v430.86 (26.21.14.3086), although I'm not sure if they're directly comparable between different GPUs and Windows versions.

**Comment by endrift** [comment]
I pushed a speculative fix, 9b0e4af7b430ee1cd4bbc9b7a37768a820c2b236, but I have no idea if it works. It may just be a driver bug with integer textures.

**Comment by ROMaster2** [comment]
Either that fixed it or updating my drivers did. I'm guessing you're using new tech for OpenGL?

Both me and @angrylion7 are fixed so I can probably close this now. Thanks for the help.

**Comment by Cibomatto2002** [comment]
I still have the problem 

Windows 10 Pro 64-bit

1023MB NVIDIA GeForce GT 720 (EVGA)
ForceWare version: 417.35

I know my drivers are old but just wanted to see if it could be fixed without updating them if not it's ok.

![test](https://user-images.githubusercontent.com/21169038/59083427-f3619a80-88bc-11e9-831b-f2eff96ffc7f.gif)

mGBA - 0.8-5813-7b12516df

**Comment by endrift** [comment]
That's a completely separate bug--notice how there are plenty of sprites on the screen. Anyway I just fixed it and pushed a fix.
