### ISSUE TITLE
Lock scale / Max. scale

### ISSUE THREAD

**Issue by tuzepoito** [mgba-emu/mgba#1493]
As of v0.7.2, the game screen stretches as far as within the limits of the window (taking into account forced integer scaling and aspect ratio) Same for fullscreen, where the area stretches as far as possible to fill the screen.
I like to play in fullscreen, surrounded by black borders to avoid distraction. However, I think the stretched game screen is a bit too large, even with integer scaling, especially since handheld game graphics are generally designed to be viewed on a smaller screen.
A solution would be to either set an option of maximum magnification in fullscreen mode, or let the user lock the scale at a given size. It's a minor issue I know, it's just that most other emulators that I know of have either feature, especially those for handheld consoles.
Nice work on the emulator by the way!

**Comment by RunisDauphin** [comment]
I know it should be Endrift who said this, but Stable version 0.7.2 lacks some of the features (such as Battle Chip Gate or the better but yet not perfect French translation) that are present in the Developpement versions that were released even before 0.7.2. My point is: have you tried a Developpement version? It may be present there.

Hope I helped ya.

Runis Dauphin

**Comment by tuzepoito** [comment]
Thanks for the tip! Anyway, I've just tried dev. version `0.8-5887-aba3ef017` on Windows 10 but the feature still doesn't seem present. All I can do is change "Frame Size" which resizes the whole window to fit the selected screen size. And if I try to change frame size while in full-screen mode (with keyboard shortcuts) it exits full-screen mode and from there, things get kinda glitchy, at least on my system; I might file a bug about that eventually.

**Comment by RunisDauphin** [comment]
I can not help you farther than that. I have always played in window mode. I remember I used a shortcut to set different sizes to the window depending on the monitor I was playing on and it worked quite well.
I do not have available the emulator for now, but as soon as I can get to my store unit, I could give you a second check.

By the way, I think that Endrift would like a bit more of specification with the affaire, because I still do not know what are you asking exactly and which platform are you refering to (I have always played to Game Boy Advance games here). Also, how big is your monitor (in resolution matters, not physical size)? Which version of Windows 10 are you using? VBA-M team asks for S.O. (Système Opératif) versions for a reason.

I hope this could help you.

Runis Dauphin

P.D.: Even though it might seem that I speak in Endrift's name, I am not. I try to get as much useful and necessary information that Endrift might need.

**Comment by tuzepoito** [comment]
I'm using mGBA 0.7.2 on Windows 10.
Display driver: OpenGL
Video options: Sync Audio, Lock aspect ratio, Force integer scaling
Screen resolution: 1920x1080
When I go fullscreen, mGBA always uses the maximum integer scaling possible for the picture to cover the full screen, like this:
![mgba-fullscreenreal](https://user-images.githubusercontent.com/47950394/64039567-34cfb200-cb5b-11e9-890f-946ca54dc820.png)

What I'd want is to "lock" the scale or specify a maximum magnification scale, for instance 3x:
(hand-edited, desired result)
![mgba-fullscreen3x](https://user-images.githubusercontent.com/47950394/64039660-6ba5c800-cb5b-11e9-81c8-c386f2582d30.png)

Hope this helps.

**Comment by RunisDauphin** [comment]
That is rather nice to have, but I think that in the majority of the cases is more worthwhile to have it in window mode. But hey, that's just me.

By the way, I now perceive what you want; but, is it me or would not it be a little too small to watch?

Hope this option could be got.

Runis Dauphin

P.D.: I may or may not have translated a bit poorly my "discours" to English, isn't it?, but I have no better substitute for my words.

**Comment by reinstallgentoo** [comment]
I'm also experiencing this bug. When fullscreen, the output is stretched to 16:9 (1920x1080 monitor) rather than scaling correctly with vertical borders. 

mGBA 0.7.2

**Comment by endrift** [comment]
Turn on lock aspect ratio.

**Comment by xZabuzax** [comment]
I also vote for having this feature implemented into this emulator.

**VisualBoyAdvance-M** has that feature implemented, it's called "Maximum Magnification", it basically allows you to change the "Screen" size of your game while playing it in "Full-Screen".

That's a pretty good feature for GB, GBC & GBA emulators IMHO because it allows you to play games of those handled devices with a smaller screen in your PC, playing it with a smaller screen in your PC "recreates" that same feeling as using the handled device.

Personally I like to change the screen size to 2x while having the emulator in Full-Screen exactly the way **VisualBoyAdvance-M** does it.

**Comment by tolik518** [comment]
For debugging games this is a very helpful feature. I'm restarting a game like 30 times an hour and it sucks always adjusting the size.
