### ISSUE TITLE
Video filters

### ISSUE THREAD

**Issue by ROMaster2** [mgba-emu/mgba#15]
[Enhancement]

Video filters like hq2x, hq3x, and 2xSaI would be nice when the resolution is larger, so it wouldn't look quite as pixelated.

Great job on everything else so far!

**Comment by purpasmart96** [comment]
Those filters are kinda garbage as of 2015, xbrz or just plain xbr is in my opinion superior to those. but a plain bilinear filter or just some support for retroarch shaders would be nice.

**Comment by CarterLi** [comment]
+1 for xbrz

**Comment by endrift** [comment]
In bugzilla already: https://endrift.com/mgba/bugs/show_bug.cgi?id=192

**Comment by ROMaster2** [comment]
While I'm certain it won't be a problem, I'll point it out since puNES doesn't support it (yet).

When enabling the video filters (like 2xBRZ, 3xBRZ), allow game/window scale be independent of it, at least in integer multiples. I like using x6 scale with a x2 or x3 video filter.

**Comment by elcorsico** [comment]
how enable video filter ? just resample vide for me
add xBRZ and other please..

**Comment by Zetchzie** [comment]
xBRZ tends to be very slow on low end Computers AdvanceMame2X filter or HQ3X is as high as I can go On my old Rig with VBA-M, ever since 2.0.1 Beta it's been a very demanding emulator

**Comment by ROMaster2** [comment]
Well it would be optional. That, and once video filters are added in it'll be easier to add more.

**Comment by DemonEyesBob** [comment]
From what I understand, right now mGBA runs (30%?) faster than VBA-M to begin with, so even more intensive filters wouldn't be as noticeable. Not to mention it doesn't make sense to not implement better filters just because they won't work on low end hardware. That's what having multiple options is for :)

**Comment by Zetchzie** [comment]
Of course all hardware has its limits. As long as we have some good non demanding filters to choose from i'm happy lol xBRZ just tends to be very slow if you don't got a modern computer. No reason not to add them just hope we get some low end friendly Filters too.

**Comment by endrift** [comment]
xBR added, but I won't be adding xBRZ as it can't be done on the GPU.

**Comment by endrift** [comment]
Closing, since all of the major featurework is done.

**Comment by inukaze** [comment]
Hi there, someone can tell me if this emulator have Video Filters / Shaders , like : lq /hq ( 2x 4x ) SuperEagle , 2xSai , Super2XSai , Bilinear , Bilinear Plus , AdvanceMAME 2X , xBRZ 2x ?

Because i can't see any option in the QT Menu for active it
Here i read "https://forums.mgba.io/printthread.php?tid=12" : Anti-aliasing is just done using OpenGL's bilinear filtering. It's usable in both the Qt and SDL versions (but you need to edit a config file to get it in the SDL version.

Which line i must use to active it ?

**Comment by Ajusa** [comment]
I also do not know how to activate these filters. They are not in any config file, from what I can see.

**Comment by seanbperiod** [comment]
Any update on this and how to activate?

**Comment by nacimgoura** [comment]
Is it still not possible to apply filters?

**Comment by endrift** [comment]
I don't understand. It's been possible for over a year. It's under Shader Settings, which is in the A/V menu (formerly) or under settings (presently).

**Comment by seanbperiod** [comment]
I don't see it for Vita. Only see a Configure Menu from the pause menu, and Screen Mode, Frameskip. Nothing related to filters.

**Comment by endrift** [comment]
It's not on Vita, since the Vita does not use OpenGL. See #448 for discussions on that. This issue only applies to desktop platforms.

**Comment by RunisDauphin** [comment]
I have tried xBR filters on a 3,40 GHz i7-2600 computer and it is not capable of moving such thing above 50%.

Could you add at least filters for those who have crappy computers?

And by the way, hq filters in other emulators (such as Kega Fusion, Mesen, SNES 9X, VBA and DeSmuME) work fine and look like if the game was made in the 7th generation.

Please, consider it.
