### ISSUE TITLE
Unable to get multiplayer link/window working

### ISSUE THREAD

**Issue by dcrck** [mgba-emu/mgba#1591]
Using the 0.8 beta-1 version, macOS

Trying to trade between two instances of Pokemon Emerald, I get the same error that #1555 shows ("Communication error... Please check all connections, then turn the power OFF and ON.") right after entering the trade room.

Thanks for taking a look.

**Comment by dcrck** [comment]
Okay, for some reason I can trade between Ruby and Emerald, but not two instances of Emerald. I guess I can work around the issue for now, but I would appreciate a fix nonetheless.

**Comment by RetroEdit** [comment]
I'm closing since this seems pretty likely to have been addressed in the past five years since this issue was filed, especially since the link cable was recently revamped.

If it's still happening, feel free to leave a comment, ideally with some saves that make it convenient to test, and then this might be able to be reopened.
