### ISSUE TITLE
Switch: Opening a ROM causes my root switch folder to wipe

### ISSUE THREAD

**Issue by kresellekey** [mgba-emu/mgba#1596]
Hey, first time posting so please let me know if I need to add more info.
Basically I have a switch on 9.0.1 firmware and mGBA runs fine, but whenever its opened it wipes all the .nro files on my switch root folder, meaning I have to turn the switch off and add back all of my applications to the switch root before playing the rom again. Anyone know of a way to help fix this? I'm also running the latest mGBA software out at the moment

**Comment by endrift** [comment]
Is your SD card formatted as ExFAT?

**Comment by kresellekey** [comment]
yeah it is, I have a 128gb micro sd card and when I triex to make it fat32 it corrupted

**Comment by endrift** [comment]
Unfortunately the Switch's ExFAT driver is prone to randomly corrupting files (you can find reports of this happening with an assortment of games too, including the Smash Ultimate Piranha Plant corruption and the Pokémon Sword/Shield autosave corruption). Try using Rufus to format it as FAT32 instead of Windows' built in utility.

**Comment by kresellekey** [comment]
ah okay thanks! Formatted it to fat32 and works without any problems now!
