### ISSUE TITLE
Permission to add mgba to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by twinaphex** [mgba-emu/mgba#1616]
Hi there,

we would like to seek your permission to include mgba as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by endrift** [comment]
Granted, though it may make sense to try and keep the port synced closer so I don't get bug reports that have already been fixed. I filed a PR to sync with latest master, and there's also the PR floating around for using gyro controls through libretro instead of libnx that I would like merged at some point.

**Comment by twinaphex** [comment]
Sure, I'd like to see that as well. It makes sense ultimately for things to be compiled from upstream if we can do it without missing any functionality.

Thanks.
