### ISSUE TITLE
Missing black row on the game "Pinball Tycoon (Europe)"

### ISSUE THREAD

**Issue by wwark** [mgba-emu/mgba#1668]
Hi,

You will find the screenshot of mgba:
![unknown2](https://user-images.githubusercontent.com/469461/74604689-96abb600-50c0-11ea-820c-77bacdc34f41.png)
From a NDS
![unknown](https://user-images.githubusercontent.com/469461/74604693-9f03f100-50c0-11ea-9555-66a86a52c3c5.png)

The missing black line is between the text zone (red dots and yellow dots) and the table of pinball.

The game switches from video mode 0 to 4 when the red dots begin.

Thanks,

**Comment by fleroviux** [comment]
The internal BG2/3 X/Y registers should only be incremented if the PPU is not in Mode 0 **and** the corresponding BG is enabled.

Because BG enable is latched with a delay of a few scanlines, the internal affine registers only start being incremented with the same delay, even when Mode 4 and BG2 are enabled at the same time.

**Comment by endrift** [comment]
Thanks for doing the legwork here @fleroviux
