### ISSUE TITLE
mGBA fails to run on Windows when located in Program Files

### ISSUE THREAD

**Issue by ketsuban** [mgba-emu/mgba#1709]
**mGBA version**: 0.8.1
**Operating system**: Windows 10 64-bit

## Steps to reproduce
1. Put mGBA in `C:\Program Files\mGBA`.
2. Run `C:\Program Files\mGBA\mGBA.exe`.

The same is likely true of `C:\Program Files (x86)`, but I didn't test it.

## What I expected
Choose one:
1. mGBA runs and any new files it creates are placed in a folder in `C:\Users\<username>\AppData`.
2. mGBA runs and any new files it creates are placed in the VirtualStore folder.
3. mGBA runs after asking for elevated privileges through UAC, and any new files it creates are placed in `C:\Program Files` or `C:\Program Files (x86)`. (This is obviously the least desirable option, since there's no reason for an emulator to need elevated privileges.)

## What I got
mGBA fails to run.

**Comment by lotharsm** [comment]
Sorry, can't replicate. Using the latest mGBA installer puts the executable in `C:\Program Files\mGBA\mGBA.exe` as defined in the Inno setup script. [1].

The files generated are properly stored in the `%appdata%\mGBA` directory.

[1] https://github.com/mgba-emu/mgba/blob/master/src/platform/windows/setup/setup.iss.in

**Comment by ketsuban** [comment]
I'm not using the installer, I'm using the 7z archive.

**Comment by lotharsm** [comment]
In this case, that's to be expected.

The 7z package works in portable mode, so it always writes in the directory where the executable is located at. In this case, it fails since it can't write to %PROGRAMFILES% due to UAC restrictions. To prevent this from happening, simply delete the `portable.ini` file from the mGBA directory, then mGBA will create the files in %APPDATA% again.
