### ISSUE TITLE
GBA games on 3DS are all mute

### ISSUE THREAD

**Issue by fanchengfei** [mgba-emu/mgba#1727]
how to switch the audio?
I use mew3ds.

**Comment by Dimensional** [comment]
For one I'd recommend switching to a New3DS instead of a mew3DS. Didn't know the console got bootlegged already. 🤣 However as far a I know, have you run [DSP1](https://github.com/zoogie/DSP1/releases/tag/v1.0) to extract the audio module from the system firmware, to allow homebrew to run?

Are you also running the program through the homebrew menu as a 3dsx or on the system menu after installing as a cia file?

**Comment by fanchengfei** [comment]
thx,I use cia.
and when I downgrade to 0.6.3,It becomes normal.
just don't know what's wrong with 0.8.3.

**Comment by endrift** [comment]
Use the DSP1 tool mentioned to dump the DSP blob. 0.6.3 used a different sound API that was somewhat unreliable. That was removed in later versions.
