### ISSUE TITLE
[feature request] Frame counter

### ISSUE THREAD

**Issue by Liger0** [mgba-emu/mgba#1728]
Hi. I see that there still isn't a frame counter on mGBA unlike other older vba emulators. 
It is useful for pokemon rng purposes, would it be possible to add it? Thank you.

**Comment by endrift** [comment]
Just to be clear, what you want is something like a current frame number displayed on the OSD or similar?

**Comment by Liger0** [comment]
Yes.

**Comment by brvsket** [comment]
how do you enable this ,,?  it says its been added but i cant find anything ,,

**Comment by endrift** [comment]
Settings > Interface > Show OSD Messages > Show frame count in OSD

**Comment by ZPokePlayz** [comment]
From what i can see in this image its not reseting the frames when the game is soft reset which is what people are hopping to see so they can see exactly what frame is hit because its just showing the current frame its on since the program has been opened which doesnt help in the slightest

![image](https://github.com/user-attachments/assets/6fc6752e-f72d-4f4a-b48e-1747e6ace09e)

**Comment by ZPokePlayz** [comment]
from what i can tell the frames are off anyway cause im trying to hit a frame thats around 7600 but the frames in mgba are saying its frame 7200
