### ISSUE TITLE
[Feature request] Wireless mode connection

### ISSUE THREAD

**Issue by Liger0** [mgba-emu/mgba#1757]
I believe the current multiplayer implementation emulates the cable link method. 
However, some game functions are coded to only be available when the wireless mode connection is detected. Having it would be a good add-on.

**Comment by Dimensional** [comment]
As far as I can tell, if you want real wireless mode, then the emulator would have to be coded to use pcap and attach or even take control of the devices physical wireless card. There was an unofficial release of DeSmume that did that, but it was buggy.

As for emulating it internally, just making the emulator think it has a wireless adapter while it really just connects to others over the internet or local network, that's something I think is more doable, though I'm just speculating. I wouldn't know where to begin to look to get something like this implemented.

**Comment by RetroEdit** [comment]
Yeah, I assumed this issue was referring to emulating the wireless adapter internally but not actually creating a network connection. After all, I don't think mGBA can currently interface with actual GBAs, and that seems to be a different and more ambitious feature request? It does currently allow emulating certain multiplayer modes with multiple instances of the emulator.

**Comment by endrift** [comment]
I'm using #472 to track implementing the Wireless Adapter itself.
