### ISSUE TITLE
[feat. request] automatic screen adjustment when forced aspect ratio

### ISSUE THREAD

**Issue by Liger0** [mgba-emu/mgba#1788]
The forced aspect ratio is a very good feature, and I think its function could be improved by automatically sizing the window so that the black portions of the screen are not present when resizing manually.
This way the emulator will waste less surface and the annoying black parts will be deleted.

**Comment by endrift** [comment]
I do not believe it's particularly possible to do this with Qt without making the resizing flow extremely glitchy, simply due to how Qt works. You can use the screen size menu option for specific integer ratios, but that's not great for non-integer ratios. The best would be an option you can click to force it to the nearest fit when you're done resizing, but that's really niche.
