### ISSUE TITLE
Missing dependencies for DEB Linux package and app launcher

### ISSUE THREAD

**Issue by HenriqueAD7** [mgba-emu/mgba#1872]
There is no app launcher (shortcut icon) in the package.

In **version 0.8.3 for Ubuntu 20.04** (I haven't checked the others), an OpenGL-related lib (**libopengl0**) is missing. Impossible to run the app.

I modified the **mgba-qt.deb** package by adding the missing dependency and the app launcher. It worked perfectly, but other users may have problems with it.

**Comment by endrift** [comment]
I should mention, the reason I haven't fixed this yet is because I haven't figured out if mGBA is _supposed_ to depend on libOpenGL or if I'm doing the linking wrong with newer CMake. I'm not intentionally linking it; it's an artifact of GLVND support in modern CMake, but I haven't quite figured out what changes I need to make as a result yet.
