### ISSUE TITLE
Madden NFL 06 and Madden NFL 07: graphical bugs on the 'coin toss' screen

### ISSUE THREAD

**Issue by angrylion7** [mgba-emu/mgba#190]
In both games the coin toss screen is utterly broken, at least in v0.3.2. To get there it's enough to select 'new game' and proceed. This video shows what it should look like:
http://www.youtube.com/watch?v=PR3sMHeuOcI
This problem exists in many emulators. VBA bug report:
https://sourceforge.net/p/vba/bugs/182/

Quote:
"It's due to a swi taking a of time for some reasons (because
it's writing to vram during display ?), and it seems pretty
harsh to emulate."

**Comment by endrift** [comment]
Looks like what's going on is that BG2PD gets set to 0x100 (correct), and then, via a DMA, set to 0, which causes the smear. What needs to happen is that the DMA should be disabled before BG2PD gets written. The DMA is disabled on the interrupt right after BG2PD gets written first, instead of before.

Not sure what's causing these to be ordered wrong.

**Comment by taisel** [comment]
Is this broken in every emulator? I swear to god if this is one of those subcycle glitch timing issues.

**Comment by RobertPeip** [comment]
Hopefully you can fix it, too.
Have written something for it here:
https://github.com/RobertPeip/FPGBA/wiki/Madden-06-07-%22Holy-Grail%22-Bug

**Comment by endrift** [comment]
Still some polish left to be done, but the simple case is fixed at least.
