### ISSUE TITLE
Blending fade doesn't work on sprites

### ISSUE THREAD

**Issue by GValiente** [mgba-emu/mgba#1905]
[blending.zip](https://github.com/mgba-emu/mgba/files/5325648/blending.zip)

mGBA 0.8.3 doesn't fade the dinosaur in the middle (rendered with a sprite):
![mgba](https://user-images.githubusercontent.com/13147012/95047629-b7278f80-06e6-11eb-8dfc-5ae24f765258.png)

Expected output:
![vba](https://user-images.githubusercontent.com/13147012/95047693-d0304080-06e6-11eb-86f4-9ac7fab7b945.png)

**Comment by endrift** [comment]
There are a LOT of corner cases when it comes to blending. Please give me more info about what you're doing and not just the ROM. Further, they may be broken in OpenGL mode, and also may have been fixed since 0.8.3 (I've made a bunch of changes...), so please test with a newer version and make sure which renderer you're using.

**Comment by GValiente** [comment]
(I think) I'm using the software renderer:
![mgba_2](https://user-images.githubusercontent.com/13147012/95048436-218cff80-06e8-11eb-958f-454df780754d.png)
![mgba_1](https://user-images.githubusercontent.com/13147012/95048432-1fc33c00-06e8-11eb-8e1b-5badfedd92fd.png)

It doesn't work with the latest development version posted on mgba.io.

If I can give you more info please feel free to ask.

**Comment by endrift** [comment]
This seems to be related to the use of target 2 on the background layers while it's not actually doing anything. That's a bug on my end.
