### ISSUE TITLE
Gameshark Code not working on Pokemon Blazed Glazed

### ISSUE THREAD

**Issue by b33-caldwell** [mgba-emu/mgba#2001]
I've been trying to find a good emulator for using cheats and this is the closest one I've gottten so far. Only three lines of codes can be active though so lots of my pokemon codes don't work (specofically one for money) I tried doing a few things redditors suggested but nothing has worked
xx thanks

**Comment by endrift** [comment]
You need to give me the codes for me to look into this.

**Comment by endrift** [comment]
These appear to be two different types of code, which is confusing that they were lumped together. Try inputting ONLY the last three lines (not the first two) in a new cheat set as type PARv3/Pro Action Replay. The first two lines are for GameShark format and tell it to treat the rest of the code as GameShark format, but they're...not GameShark format codes.

**Comment by flingrocks** [comment]
Hardly worth mentioning, but it seems that infinite money cheat is missing a patch code needed for decrypting amounts (works without, but money would be some strange value). A mastercode hook is not crucial in this instance. The complete code probably is:
A57E2EDE A5AFF3E4
1C7B3231 B494738C
_525F4CDD 578E4EC7_
_1C7B3231 B494738C_
732BCD9E 2D619E45
C051CCF6 975E8DA1

If mistakenly added with Add GameShark instead of Pro Action Replay, you'll find that most of the lines are skipped. Though they won't at all mean the same, the few lines that stay are those that resemble possible GameShark types when decrypted using GSv1 seeds. Arguably, any candidate code lines being skipped over should be a red flag to the user of a possible entry mistake! (Should it occur, could we denote this somehow before it enables the first time?)

**Comment by endrift** [comment]
There are definitely usability concerns with adding cheats that I need to address.

**Comment by piperun** [comment]
Since this is essentially a pokemon emerald hack, I noticed that mGBA keeps removing:
**B749822B CE9BFAC1**
from:
```
B749822B CE9BFAC1
A86CDBA5 19BA49B3
```
Which you can find here:
https://www.pokemoncoders.com/pokemon-emerald-cheats/

**Comment by Dragobalt** [comment]
> You need to give me the codes for me to look into this.

I really new help my action replay max device if anyone cane

**Comment by endrift** [comment]
This issue is pretty outdated and contains a hodgepodge of different codes, most of which contain issues with the codes themselves. I'm just closing this. New issues for specific codes are fine.
