### ISSUE TITLE
Port mgba for ESP32

### ISSUE THREAD

**Issue by jfm92** [mgba-emu/mgba#2011]
Hi, 

Maybe is crazy, but just for experimenting, I'm trying to port mgba to the ESP32. This module can handle pretty well GameBoy/GameBoy Color, NES, and Sega Master System. Obviously, those emulators are much simpler and 8bit.
By now, I achieve to compile mgba with the ESP-IDF IDE and add it as a library.

So, I have a few questions to continue with this experiment:
- Is mandatory OpenGL support? I've read on the mGBA 0.8.0 release log the usage of OpenGL to upscale the resolution of each frame allowing up to 4k, but I'm not sure if this is required for render the frame on the original resolution. 
- Where I can find a port guide or a basic example that shows the emulator initialization? I saw in the folder platform, there are a few initializations for different devices, but I was wondering if exist a guide or a generic example.

I know that my question is a little generic, and this experiment is in a very early stage, but It would be awesome if mgba could run on such a constrained device.

**Comment by endrift** [comment]
I _highly_ doubt it'll be performant at all. However, you can find example code in src/platform/example. I know there's a [downstream fork](https://github.com/44670/mgba-k210) that strips out some of the accuracy for faster gameplay on the K210, though I'm not really sure what the K210 is and I'm not sure I'd recommend it as a starting point. I think @oskenso also has some porting experience based on conversations we've had in the past.

**Comment by profi200** [comment]
To be fair the poor performance on the Vita might be due to other bottlenecks. The much older ARM11 MPCore on the 3DS just about manages fullspeed in many games at 804 MHz.  There is a possibility Sony cheaped out on stuff like the bus width (3DS has a 64 bit bus).

But i doubt the ESP32 got any of that horse power. Even the new Game & Watch recently released can emulate GBC on a microcontroller so that's not the most demanding.

**Comment by Oskenso** [comment]
I once experimented with mgba on a raspberry pi zero with an oled display connected via gpio (parallel/no-spi). It ran gbc rather well and gba  games were a tad slow, but could have been optimized.

The first thing i'd do is explore mgba/src/platform, in there you'll find a few examples of how to initialize and interact with mgba core. For example the SDL (https://github.com/mgba-emu/mgba/blob/master/src/platform/sdl/sw-sdl1.c) is a great place to start with rendering.

My first attempt at using the seps525 display -> https://github.com/Oskenso/mgba/blob/seps525/src/platform/sdl/sw-sdl.c

Eventually, since the platform was a pi zero and with that we get a kernel framebuffer... I went with drawing to /dev/fb0 and writing another program to read and send commands to the display -> https://github.com/Oskenso/mgba/blob/drawToFramebuffer/src/platform/sdl/sw-sdl.c

This supported bilinear filtering, but was rather slow so I opted to skip a few lines to render as shown in 'osky_resize()'

I hope this helps! Please feel free to ask any and all questions

**Comment by endrift** [comment]
While you're welcome to keep discussing, this isn't an _issue_ with mGBA itself _per se_ so I will be closing this. Feel free to keep discussing in this bug report, or Discord or the like, but it's not beneficial to keep it open.
