### ISSUE TITLE
Support for Apple M1 chip?

### ISSUE THREAD

**Issue by sofakng** [mgba-emu/mgba#2019]
Has anybody been able to compile a native version of this for the Apple M1 chip?

I wouldn't be surprised if the existing version works good under Rosetta so having a native binary would be nice for extra speed or better optimization (battery life, etc).

**Comment by endrift** [comment]
I would like to do this but for various reasons it's not particularly feasible at the moment. For one thing, my build infrastructure definitely can't do it yet, and I don't have the spare funds to buy Mac hardware. There's a Patreon goal at the moment so I can buy and maintain that hardware, but it's $90/mo away from being met.

**Comment by sofakng** [comment]
Ahhh, OK.  I can try to compile it and see what happens, but I took a quick look at the dependencies and I'm not sure all of them compile cleanly on the M1 which is probably the biggest issue.

Does mGBA use any assembly that would need to be rewritten?

**Comment by endrift** [comment]
No it doesn't. You may run into an issue where it compiles but crashes when you try to run it, namely #1754. This happens because Apple decided to break OpenGL on threads entirely, which mGBA depends on. I'm not sure how to fix this yet.

**Comment by sofakng** [comment]
Ahhh... that's not good.

If you figure out anything and would like me to test I'd be glad to try and compile and test it.  (I've also joined your Patreon;  Thanks for all of your hard work!)

**Comment by sofakng** [comment]
If the OpenGL implementation on MacOS is broken, would it possibly work better using a libretro version which I think can use Vulkan (or Metal API?)

**Comment by endrift** [comment]
This should be done, except for some potential issues with the OpenGL renderer I've run into (appears to be fine after a reset??) and not having a builder set up yet. I'm leaving it open until the builder is set up though.

**Comment by endrift** [comment]
Builds for modern macOS are now available on the website.

**Comment by fooness** [comment]
_Hello everyone. Please excuse me sliding into this closed issue, but I thought my question is better suited here than in a newly opened issue; at least for now until I know more about this subject. I’m on macOS Ventura `13.2.1` on Apple M1._

Since Apple basically deprecated OpenGL in macOS, **should we choose the “Software” driver in the settings wherever “OpenGL” is selected by default?** That is, in the “Audio/Video” tab in the “Video” section for **“Display driver”**, as well as in the “Enhancements” tab for **“Video renderer”**.

_Please let me know in case I should, in fact, open a new issue for this; including what information I could/should provide._
