### ISSUE TITLE
ABI versionning policy

### ISSUE THREAD

**Issue by Celelibi** [mgba-emu/mgba#2042]
Hello,

It looks like libmgba is meant to be used as a library. The cmake files can install the header files and the shared library gets a SONAME ending with the ABI version, which is all good technically. But apparently, the only thing preventing the inclusion of a libmgba-dev package in Debian is the lack of an official commitment to change the SONAME on every ABI change.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=982147

So if the project is ready to make this commitment, maybe a few lines could be added to the README or something?

Best regards,
Celelibi

**Comment by endrift** [comment]
Considering there aren't many projects that depend on libmgba yet I haven't explicitly stated it anywhere but I do indeed maintain API and ABI compatibility within the same minor release of libmgba, and have been doing so for several years, often to the detriment of releases--there are times where I want to backport fixes to a point release but have to hold them back since they would break ABI. There are a bunch of instances of this floating around that I can go hunt down if needed, but it's basically always been the case and will continue being the case while this version scheme is in place.
