### ISSUE TITLE
ips patch support

### ISSUE THREAD

**Issue by Northwemko** [mgba-emu/mgba#2317]
Game Boy Player  enhanced games such as Pokemon Pinball - Ruby & Sapphire and more game rumble
see this link
https://gbatemp.net/threads/release-pokemon-pinball-ruby-sapphire-ez-flash-omega-de-rumble-patch.600144/
https://gbatemp.net/threads/gamecube-gba-rumble-games-and-rom-hacked-rumble.589863/
someone make ips ,but only do for EZ-FLASH OMEGA Definitive Edition work,i'm try mgba,doesn't work,can support be added in future updates?

**Comment by endrift** [comment]
Both GB Player enhancements and IPS patches have been supported for several releases by now. I'm not sure what the problem is.

**Comment by CasualPokePlayer** [comment]
Seems like these patches work by using cartridge rumble over GB Player rumble. This probably wouldn't be able to be autodetected by mGBA, so the issue is likely just a case where the user didn't set overrides to enable rumble.

Of course this is moot anyways since you can just use normal GB Player rumble in mGBA :P
