### ISSUE TITLE
Known fast forward issue

### ISSUE THREAD

**Issue by GrudgeMaxx** [mgba-emu/mgba#2347]
Hello,

As is known, I am experiencing an issue where held fast forward does not function.  The game will speed up for a few frames, then return to normal speed.  At that point, all fast forward does is make the audio choppy, but audio returns to normal whenever fast forward is not held.

Using 0.9.2.  Windows 10.  I have seen this issue reported a few times, dating back to 0.8.0, but the issue persists.  Do we anticipate this being fixed anytime soon?  Let me know if there's any further information I can provide.

Thank you

[mGBA bug report.zip](https://github.com/mgba-emu/mgba/files/7491753/mGBA.bug.report.zip)

**Comment by endrift** [comment]
Please try a dev build. There have been more fixes applied since that will be making it into 0.9.3. But also fast forward and the OpenGL enhancement renderer don't always get along, so you may need to pick one that's preferable for the time being. That _should_ be sorted out, but I cannot guarantee it.

**Comment by endrift** [comment]
Closing due to lack of reply.
