### ISSUE TITLE
Various problems with Classic NES games

### ISSUE THREAD

**Issue by zambonin** [mgba-emu/mgba#236]
As per #232, the `[f1][a1]` and `[f1] (Save Type)` Zelda dumps now just give a white screen -- nothing on logs or output.

I tested some japanese ROMs too and they also produce the game pak error (or at least looks like it). Would it be necessary to test all of the ROMs?

`Famicom Mini - Vol. 23 - Metroid (J).gba` and `Famicom Mini - Vol. 23 - Metroid (J) [f_4].gba` hang on a black screen with some choppy audio. Logs give me a lot of these:
```
[GAME ERROR] GBA Memory:	Bad memory Load32: 0x78404845
[GAME ERROR] GBA Memory:	Bad memory Load32: 0x78404851
[GAME ERROR] GBA Memory:	Bad memory Load32: 0x7840485D
[GAME ERROR] GBA Memory:	Bad memory Load32: 0x78404869
```
However, a lot of other games (haven't tested all) are fixed now. Thanks. :)

**Comment by angrylion7** [comment]
As of git 2016-06-01, Super Mario Bros. and Excitebike from Classic NES Series still exhibit flickering graphics on their title screens and elsewhere. This has been mentioned in #232, but that issue was closed, so I thought I'd post it here.

**Comment by endrift** [comment]
- `Famicom Mini - Vol. 23 - Metroid (J).gba` seems to have been fixed at some point. It works fine now.
- The `[fx]` variants are unsupported, as they're hacked up ROMs that weren't ever guaranteed to work on hardware in the first place.
- The flickering is temporal antialiasing. This is by design, as the GBA screen has ghosting that blends the frames together. However, modern computers don't, so it shows through.
