### ISSUE TITLE
Game Boy Player support broken

### ISSUE THREAD

**Issue by autofire372** [mgba-emu/mgba#237]
I was playing Pokémon Pinball to test mGBA's GB rumble support on my Windows 8.1 partition, and my Razer Sabertooth Elite did not rumble. The same controller happily rumbled when I tested the game on my Linux Mint partition.

It would appear that mGBA's rumble implementation does not support Xinput force feedback on Windows, only Dinput rumble.

Note: before you ask, I am perfectly aware that Microsoft's Xinput is not the same thing as Linux's xinput.

**Comment by endrift** [comment]
You've come to the wrong conclusion. I think the problem is more how I try to smooth out the rumbling (mostly for PWM things, such as Drill Dozer and Game Boy Player-enabled games), which has been known to cause issues with some controllers. I'll need to find a better way to do it.

Also sometimes rumble is just broken in Pokémon Pinball.

**Comment by endrift** [comment]
Game Boy Player functionality is currently broken.

**Comment by endrift** [comment]
I've fixed GBP support and verified that my 360 controller rumbles via Xinput.
