### ISSUE TITLE
AppImage builds

### ISSUE THREAD

**Issue by LunarLambda** [mgba-emu/mgba#2420]
From what I gathered, people on more non-standard Linux systems (chromeOS, non-glibc systems, possibly things like NixOS?) have difficulties installing or updating the dependencies needed for mGBA.

It would be convenient for those people if portable AppImage builds could be provided, that bundle all necessary libraries into a single executable package. (Or alternatively, if possible, statically linked builds?)

From what I have seen doing so wouldn't be terribly difficult.
It may even make having builds for 5 or so versions of Ubuntu redundant.

I briefly skimmed the AppImage docs and it seems pretty well covered:
https://docs.appimage.org/packaging-guide/index.html

**Comment by endrift** [comment]
There's been some discussion of this in various places. One of my concerns is that mGBA as shipped is two separate programs (the Qt frontend and the SDL frontend) that share libmgba.so. I'm unsure how best to handle this with an AppImage; perhaps just ship two separate ones, or leave the SDL frontend out since most people using AppImages probably would just want the Qt GUI.

**Comment by LunarLambda** [comment]
I would probably say only ship the QT frontend, yeah

Providing two separate images would also be possible but obviously is duplicated effort. I don't know how big the userbase for the SDL frontend is anyway

**Comment by Jan200101** [comment]
another solution would be bundling both executables within the app image and execv'ing one of them from a wrapper application

**Comment by endrift** [comment]
AppImage builds are available as of 770b121b10ba9ff500e1e8ad946d57b87d8e58dc, but might need some more testing to figure out if there are bugs. One known problem is that themes don't work properly, but this seems to be inherent to AppImages.
