### ISSUE TITLE
Weird Audio Stuttering in Every Game

### ISSUE THREAD

**Issue by LunaDook** [mgba-emu/mgba#2483]
Having a weird issue that just cropped up recently where every game will run with weird audio stutters although emulation seems to be running full speed, regardless of audio backend, framerate sync settings, etc.

I assume it's an issue with something on my end but I'm stumped as to what it could be. Please find attached a report file I generated while running Mario Kart Super Circuit. I would link a video also showing this off but when I went to record in OBS the issue vanishes when doing the encoding of the recording, and then returns when I stop recording in OBS within about a minute or two. This also seems to extend to doing other things that tax my processor heavily.

[report thing.zip](https://github.com/mgba-emu/mgba/files/8359106/report.thing.zip)

**Comment by Instandhaltung** [comment]
I don't know if it's the same issue, but I also have audio crackling while playing Mario Bros 3 (SMB Advance 4). This first occurred after updating the retroarch core. Haven't tried other games yet though.

**Comment by LunaDook** [comment]
I realized that I was running a version behind by accident, sorry about that. The issue still occurs on 0.9.3 in the same way, and I can confirm it seems to be an issue with mGBA only as I have tested some games in BGB and generally tested audio on my system and am unable to find a similar issue there. 

From my point of view, it's looking like the game is running ever so slightly off the FPS target that is selected, which may be causing these issues(?). It seems to be solid at 60 when OBS is running and doing CPU x264 encoding, then goes down to anywhere from 58.5 to 59.1-ish and kinda just hovers around there based on the taskbar. I'm making assumptions though, so do take me with a grain of salt. Please find attached an updated report thing.zip lmao

[report thing 2.zip](https://github.com/mgba-emu/mgba/files/8360164/report.thing.2.zip)

**Comment by LunaDook** [comment]
Sorry to double post so soon, but I just had mGBA stop execution of the game right as I posted the last comment. This was also happening on 0.9.2 but I had seen there was apparently issues with 0.9.1 and 0.9.2 that could cause such, so I didn't mention it in the above post. I know it's (likely) unrelated to the above issue, but thought I'd mention it here for completion sake, in case the two do happen to have some relation.

**Comment by Instandhaltung** [comment]
All right, then it's really not the same issue I think. My audio crackling happens on Switch in retroarch and is a relatively new problem (I think). 😅

**Comment by pcone** [comment]
I've noticed this happening recently as well. The gameboy advance starting animation has normal audio for a little bit and then just outputs static, and then audio in games seems to be messed up. Some it mostly sounds normal but with extra distortion but in Breath of Fire 1 specifically I get nothing but occasional clicking noises.

I've had the same version of mGBA installed on this windows PC for a while (0.9.3) and I was playing Breath of Fire just fine a couple of months ago and recently came back to it to find I suddenly had this issue - I wonder if this has been caused by a windows or video card driver update being incompatible for some reason.

If it helps I'm running a 6800xt GPU and a ryzen 3600 cpu, and my current video card drivers are version 22.3.1

**Comment by LunaDook** [comment]
I had to do a Windows re-install for various other reasons (had some other weird issues that were unable to be fixed with the standard DISM, sfc, chkdsk, etc) and after the reinstall things seem to be completely fine on my end now. I'm gonna close this as my issue is resolved now.
