### ISSUE TITLE
i try to run my custom GBA game (made from scratch btw) is it because they mGBA and scratch use different languages or is it something else?

### ISSUE THREAD

**Issue by LucasAnimates** [mgba-emu/mgba#2652]

**Comment by RetroEdit** [comment]
When you say "made from scratch" are you talking about the Scratch block-base visual language ( https://en.wikipedia.org/wiki/Scratch_(programming_language) )?

If so, then mGBA doesn't support and will probably never support the Scratch exported format (`.sb3` currently). Because mGBA is mainly designed for software media supported by the Game Boy Advance, so basically GBA games, GB games, GBC games, and a few other related things. Scratch uses a very different format for games.

**Comment by Testsr** [comment]
What tools did you use? URLs would be nice.

**Comment by LucasAnimates** [comment]
Scratch, scratch/edu.com

**Comment by Testsr** [comment]
The answer is that Scratch and  GBA speak very different languages. Unless you have a converter for Scratch code to GBA code, you won't be playing your projects in mGBA.

**Comment by LucasAnimates** [comment]
Thanks for the help!
