### ISSUE TITLE
mGBA just not loading on Chromebook (via Debian 11 Crostini, with software-properties-common installed)

### ISSUE THREAD

**Issue by PaperVb64** [mgba-emu/mgba#2699]
The .deb installs everything, and i tried every file in the tar.xz on the site. The QT version installs, but doesn't load. What did i do wrong?

**Comment by endrift** [comment]
First of all, those tar.xz files are for Ubuntu. Debian is not Ubuntu, so there isn't a good direct match. The closest match would be the focal debs, but they won't work because of Ubuntu randomly renaming one of the packages (libzip4 to libzip5), which Debian didn't do (there's no libzip5, only libzip4). This means it won't work without also installing Ubuntu's libzip5, which while theoretically possible, is somewhat risky. So what you did wrong was installing them in the first place. The AppImage should work, hopefully.

Second of all, this isn't a support forum. It's a bug tracker.
