### ISSUE TITLE
mgba Sprites Lighter?

### ISSUE THREAD

**Issue by TsukiruP** [mgba-emu/mgba#2723]
I've used mgba and VBA to rip sprites from the Sonic Advance games. mgba's multi-pak support was a lot easier. But I've only now noticed that mgba's sprite viewer gets sprites that are just slightly brighter than VBA's. I tried seeing if this was already mentioned but couldn't find anything (discussion about GBA lighting or brightness is surprisingly about something else entirely).

**VBA**
![image](https://user-images.githubusercontent.com/104665617/201766553-81662768-ca84-48c0-80d5-b3cbe4ead72c.png)

**mgba**
![image](https://user-images.githubusercontent.com/104665617/201766695-c2495e44-b210-4762-ad6d-7ea893fd4630.png)

Doesn't seem to be impacted by shaders, and this has occurred on a fresh download of 0.10.0 portable Windows 64bit.

Not really concerned about what's more "accurate" but most sprite rips I've seen and used already follow VBA's colors and wonder if there's anyway to get those. Not really interested in ripping everything from Advance 3 with mgba or recoloring sprites.

**Comment by endrift** [comment]
This is due to how mGBA and VBA extrapolate from 15-bit color into 24-bit color. VBA leaves the bottom bits empty, which is simpler math but then 15-bit white becomes slightly darker than 24-bit white (#F8F8F8 instead of #FFFFFF). mGBA tries to fill in the bottom bits a bit more intelligently. There is no setting for this since the code to do this is too deeply ingrained and cannot be swapped out easily. Further, there is already an open issue about this: #2193. The only way this would change is if mGBA switches to using CLUTs, which I intend to look into at some point.

**Comment by TsukiruP** [comment]
I see now. Thank you for explaining, I'll refrain from ripping and how progress goes well and all that jazz.
