### ISSUE TITLE
[Scripting API] Execution position callback

### ISSUE THREAD

**Issue by Yukitty** [mgba-emu/mgba#2742]
Please add a scripting callback for when the program counter is about to execute specific requested memory address(es). Like a debugger breakpoint which calls Lua and then execution continues as normal.

Currently the only callbacks are when input is polled (which is unreliable due to lag frames) or when the frame is completed and already rendered (which is too late for some things), and my only alternative is to check the `pc` register manually and loop `step()` from the start of the previous frame, which I'm assuming is a _very very bad_ idea for multiple reasons.

I intend to do things such as sort my own extra sprites directly into OAM immediately after the ROM program has finished with its own sprites, detect when a scene transition is being called, and when other events are triggered that don't necessarily happen every single frame, or which I would like to redirect or reconfigure in memory just before they happen.

**Comment by endrift** [comment]
This is planned, pending debugger integration

**Comment by v1993** [comment]
I'd like to add that I'm very interested in this feature, ideally alongside watchpoints.

I'm currently working on a project to intercept music playback and communicate it to a companion program that will play hi-def audio in place of original soundtrack when available. It's possible (if a little awkward due to needing to pass command line argument to enable networking) to do this using BizHawk with its mGBA core, but I'd much prefer to stick to pure mGBA.

**Comment by endrift** [comment]
These actually both already exist in 0.11-dev; I must have forgotten to close this.

**Comment by endrift** [comment]
I should note that I do plan to add an MSU-1-like for the GBA at some point, but it's still a ways out.

**Comment by v1993** [comment]
Oh, that's excellent to hear! Is there updated documentation for that anywhere? `docgen`'s raw output is not exactly convenient to navigate.

**Comment by endrift** [comment]
https://mgba.io/docs/dev/scripting.html it's also pretty unwieldy. I need to improve it.
