### ISSUE TITLE
Multiplayer: Warn when two players use the same save file

### ISSUE THREAD

**Issue by ahigerd** [mgba-emu/mgba#2750]
When two multiplayer windows use the same save file, they're pretty likely to scribble inconsistent data into the save file.

There's no way to fix that behavior, but the impact on the user can be mitigated by issuing a warning if more than one window has selected the same save file. Alternatively, we might want to consider disabling the options that are in use in other windows so that they can't be selected.

**Comment by endrift** [comment]
Looking at [the code[(https://github.com/mgba-emu/mgba/blob/ee21eed29c4acec6c58b9d1c9f06a3b3ac37c2c5/src/platform/qt/CoreController.cpp#L292-L297), it looks like that's only supposed to happen if there's only one player. HOWEVER, in the case that player 1 starts a game with a player >1 save, then opens the window and loads the game, it can still go wrong.

Hypothetically, I could swap that player's save with the .sav instead of the .saX it's using instead of a warning, but that might be confusing too.

**Comment by qwetboy10** [comment]
Hi. I'm a UT Student taking the virtualization course. Could I ask to work on this issue? Thanks.
