### ISSUE TITLE
Crashes when I change setting from the Tool>Setting menu.

### ISSUE THREAD

**Issue by HEETheet9** [mgba-emu/mgba#2794]
When I go to Tool-->Setting and then click Apply or OK the emulator crashes. This even happens if I had not changed any settings.

**Comment by Felipefpl** [comment]
I can confirm this too. It doesnt matter what you change, the emu freezes and crash.

**Comment by endrift** [comment]
I'm going to need a bug report zip (File > Report Bug) before I can even start to do anything with this report.

**Comment by Felipefpl** [comment]
Here it is. The emu also crashed after i closed the bug reporter and then the emu itself.

[mgba.zip](https://github.com/mgba-emu/mgba/files/10475653/mgba.zip)

**Comment by endrift** [comment]
That is some mightily terrible hardware you've got in that computer. It'll be hard for me to procure similar enough hardware to debug that crash.

**Comment by Felipefpl** [comment]
> That is some mightily terrible hardware you've got in that computer. It'll be hard for me to procure similar enough hardware to debug that crash.

Hehe, indeed, my computer is too old and i dont have $$$ to buy a decent one. :p - dont worry about that.

The only solution is wait for the other guy.

**Comment by endrift** [comment]
@Felipefpl can you check if turning off the OSD in Interface *before* saving avoids the crash? See also #2136.

**Comment by Felipefpl** [comment]
@endrift - I did as you suggested and it didnt work, i also changed to software/open gl/open gl 1x based on what was talked on #2136 and it didnt work neither. :/

I have a suggestion but you wont like it since it demands some work: you could add bugtrap to mgba, please see below.

https://github.com/bchavez/BugTrap

Unlike what is written it works for any kind of software, not only .NET, you can even set up a server where the detakled crash logs with stack dumps can be sent, i believe this could help you/everyone who is a dev A LOT, i mean, if you dont mind to try and the extra work you'll have to do to integrate it into mgba. ;) :+1:

**Comment by HEETheet9** [comment]
I have good pc but still it is crashing. :(

> That is some mightily terrible hardware you've got in that computer. It'll be hard for me to procure similar enough hardware to debug that crash.

**Comment by endrift** [comment]
@HEETheet9 I still need that bug report zip from you.

**Comment by HEETheet9** [comment]
> @HEETheet9 I still need that bug report zip from you.

how do i get that
and what is that

**Comment by HEETheet9** [comment]
> @HEETheet9 I still need that bug report zip from you.

[mGBA Bug Report.zip](https://github.com/mgba-emu/mgba/files/10491725/mGBA.Bug.Report.zip)
is this that

**Comment by endrift** [comment]
That depends. Did you generate it using the instructions I provided? Or did you just google "mgba bug report zip" and upload a random one you found? Because if it's the latter, no, you need to actually generate it yourself. If it's the former, then your CPU is actually trash (Sandy Bridge is 12 years old) and you should try doing the thing I asked felipe to do in [this comment](https://github.com/mgba-emu/mgba/issues/2794#issuecomment-1399682113)

**Comment by HEETheet9** [comment]
> That depends. Did you generate it using the instructions I provided? Or did you just google "mgba bug report zip" and upload a random one you found? Because if it's the latter, no, you need to actually generate it yourself. If it's the former, then your CPU is actually trash (Sandy Bridge is 12 years old) and you should try doing the thing I asked felipe to do in [this comment](https://github.com/mgba-emu/mgba/issues/2794#issuecomment-1399682113)

I open mGBA and go to Bug Report and then save the file

**Comment by HEETheet9** [comment]
> Please read the entirety of what I said.

I generate it

**Comment by HEETheet9** [comment]
> Please read the entirety of what I said.

I did it with the instructions you gave

**Comment by endrift** [comment]
You still haven't done what I asked in the last sentence.

**Comment by Testsr** [comment]
@HEETheet9 Your CPU is very old, like 2011 old. What he asked you to do is to try turning off "Show OSD messages" in Interface. Does that avoid the crash?

**Comment by CursedSilicon** [comment]
@HEETheet9 You need to open mGBA and go `File > Report Bug`

Then attach that bug here on github. Googling it wont work

**Comment by Testsr** [comment]
sorry, forgot gender

**Comment by HEETheet9** [comment]
> @HEETheet9 Your CPU is very old, like 2011 old. What she asked you to do is to try turning off "Show OSD messages" in the Interface menu. Does that avoid the crash?
Ok

**Comment by endrift** [comment]
If you're not going to answer my questions then I can't help you.

**Comment by HEETheet9** [comment]
> If you're not going to answer my questions then I can't help
I tried to turn off Show ODS Message but it still crashed

**Comment by Felipefpl** [comment]
Why this was blocked? I downloaded the latest nightly and the crash when changing or clicking Ok in the settings still happen.

**Comment by Felipefpl** [comment]
I tried the latest build and the problem is gone, thank you for the fix. But i noticed 2 small problems in mgba now:

1 - When you click on "Apply" in the settings the settings' window closes, before it remained opened.

2 - The languages' list shows the brazilian portuguese language as "português" when it should be "Português Brasileiro" to avoid confusion with the portuguese spoken in Portugal.
