### ISSUE TITLE
Compile error at "Linking C shared library libmgba.so"

### ISSUE THREAD

**Issue by ivasim** [mgba-emu/mgba#28]
Hi, since recently I am having this problem and cannot compile mgba.
Cmake passes without any signs of a potential error, I hope, but make crashes at 56%.
I'm sorry if this is a trivial problem, I'm not an experienced linux user...

Cmake process:
> -- checking for one of the modules 'libedit'
CMake Warning at CMakeLists.txt:57 (message):
 Requested module libedit missing for feature USE_CLI_DEBUGGER.  Feature
  disabled.
Call Stack (most recent call first):
  CMakeLists.txt:148 (find_feature)

> -- checking for one of the modules 'libzip'
CMake Warning at CMakeLists.txt:57 (message):
  Requested module libzip missing for feature USE_LIBZIP.  Feature disabled.
Call Stack (most recent call first):
  CMakeLists.txt:152 (find_feature)

> -- checking for one of the modules 'MagickWand'
CMake Warning at CMakeLists.txt:57 (message):
  Requested module MagickWand missing for feature USE_MAGICK.  Feature
  disabled.
Call Stack (most recent call first):
  CMakeLists.txt:153 (find_feature)

> -- Feature summary:
-- 	CLI debugger: OFF
-- 	GDB stub: ON
-- 	Video recording: ON
-- 	GIF recording: OFF
-- 	Screenshot/advanced savestate support: ON
-- 	ZIP support: OFF
-- 	7-Zip support: ON
-- 	Better audio resampling: ON
-- Frontend summary:
-- 	Qt: ON
-- 	SDL (2): ON
-- 	Libretro core: OFF
-- 	Profiling: OFF
-- Library summary:
-- 	Static: OFF
-- 	Shared: ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mgba/build

Below is a short excerpt of compile process containing an error messages.

> [ 56%] Building C object CMakeFiles/mgba.dir/src/third-party/lzma/7zStream.c.o
Linking C shared library libmgba.so
/usr/bin/ld: /usr/local/lib/libavcodec.a(avpacket.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libavcodec.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/mgba.dir/build.make:1940: recipe for target 'libmgba.so.0.3.0' failed
make[2]: *** [libmgba.so.0.3.0] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/mgba.dir/all' failed
make[1]: *** [CMakeFiles/mgba.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by endrift** [comment]
This is a problem with your libav/ffmpeg installation. It's trying to link against a version of libavcodec that it can't link against as-is. You have three options:

* Link against a different libavcodec. This might involve recompiling it, or, if you built it yourself (which appears to be the case), uninstalling it and using one from your package manager. This is what I recommend.
* Compile libmgba as a static library instead of a shared one. This involved doing cmake -DBUILD_STATIC=ON -DBUILD_SHARED=OFF.
* Disabling linking against libavcodec. This involves doing cmake -DUSE_FFMPEG=OFF.

Since the library is in /usr/local, it's likely one you built yourself at one point, so taking care of that library is the best approach.
