### ISSUE TITLE
[Feature request] Expand mGBA's save converter to cover different GBC SAV+RTC formats

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#2840]
A problem I had recently: To use Mystery Gift in Pokemon Crystal Clear, I had to use GBE+ (which emulates the Infrared sensor).
But that emulator converts 32KB sav file (save+RTC) used by mGBA to its own 128KB format, which is incompatible with save editors like pkHex.

mGBA can read and use the GBE+ 128KB SAV (I guess the extra data is appended at the end, in a compatible way) but the save converter can't turn it back to the original 32KB format.

Ideally, the converter should offer the option of trimming the extra RTC data back to the barebones 32KB.

**Comment by endrift** [comment]
This sounds like a GBE+ bug, potentially. @shonumi

**Comment by shonumi** [comment]
@RafaelTrepaUnCarballo Sorry I haven't responded earlier on Reddit. Anyway, GBE+ forces 128KB saves because it was a very, very old design decision back when I first attempted  GB emulation over a decade ago. It was to (rather bluntly) account for any game that potentially had misleading ROM headers. You can manually pare down the file via command line tools on Windows/Linux, or with a hex editor to get a 32KB file.

Ideally though, the onus should be on GBE+ to export a slimmed down save file. I'd suggest closing this issue and making one on GBE+'s repo. The save format was not intended to be interoperable with other emulators at the time, since it was just a personal project that kinda turned into something more, so it shouldn't be mGBA's job to import this. There's already a dedicated function to export saves is GBE+, all that's needed is to set the correct size.
