### ISSUE TITLE
Audio Improvement on PSV

### ISSUE THREAD

**Issue by mohasi** [mgba-emu/mgba#2842]
Hello endrift, I understand that multiple reports have been made about the issue I am experiencing, which I myself have reported in the past. I appreciate your response explaining that the PSV is not powerful enough to emulate accurately at 100%, and I understand that.

However, I have managed to overclock my PSV to 500Mhz without any issues such as overheating or quick battery drain. Currently, I am running Advance Wars, which runs at 55-60 fps, often at 60 or close to it. I feel it is almost perfect, and with a few adjustments, it could lock to 60 fps and eliminate the audio issues.

I am aware of a plugin for the PSV that unlocks the 4th core. Although you might say that mGBA is single-core and the 4th core does not matter, is it possible to offload some tasks to another core?

Another idea I have is to reduce the frame rate to a locked 30 fps and improve the audio. As a non-developer, I believe that if half the time is spent rendering the frame, some processing power would be left for audio. Most RPGs/strategy games, which I mainly play, would work well at 30 fps.

Finally, I understand that GPU acceleration might be challenging due to time constraints, but I wanted to suggest it nonetheless.

The PSV is a fantastic handheld that is loved by its owners, and mGBA is the best GBA emulator available for it. I kindly request that you consider adding some improvements to make it perfect.

Thank you.

**Comment by endrift** [comment]
mGBA already uses a second core for graphics processing. There's not much more it can do, and it has no use for a fourth core, as it doesn't even use a third core already.

The "frame rate locking" you are describing is equivalent to setting frameskip to 1, which you can already do. Due to how emulation works, you can't have the framerate run separately like it does with modern video games.

GPU acceleration is effectively a non-starter without tons of effort.

There isn't really much I can do here.
