### ISSUE TITLE
[Question] How can one limit the frames per second in libmgba?

### ISSUE THREAD

**Issue by sergiotarxz** [mgba-emu/mgba#2854]
## How can one limit the frames per second?

I have been trying to set the fpsTarget config option to low values such as 1.f, 30.f or 0.1f but it appears to have to effect over the speed of the emulation.

I have seen something about mCoreSync, but I am not sure about how this work and if I can use it using the callback `mCoreThread.frameCallback` to get the frames at the correct timing. 

Thank you, Sergiotarxz.

**Comment by endrift** [comment]
This is not a support forum. If you want support using libmgba, please use the forums or the Discord.

That said, you need to provide a way to throttle it otherwise it...won't throttle. That's what mCoreSync is for. It can limit frame timing based either on audio rate or video rate, but you need to on the other side actually provide a limiting factor, e.g. the audio driver or vsync, respectively.
