### ISSUE TITLE
(Idea) Color Settings

### ISSUE THREAD

**Issue by TsukiZero** [mgba-emu/mgba#2960]
Basically the ability to tune contrast, brightness, "true white", gamma, "colorblind mode", etc. Or at the bare minimum a "darken" feature for the case a game feels too bright.

**Comment by endrift** [comment]
Check the shaders section of settings.

**Comment by TsukiZero** [comment]
There is no Shaders section.

**Comment by endrift** [comment]
In general, you should only be running the OpenGL (not 1.x) display driver, as it's the only one that can support features like this without incurring significant overhead. It offloads the processing to the GPU, which is not possible otherwise. The others are only there for fallback in case of incompatibilities, but any hardware from the last decade or so should be able to manage the OpenGL driver.
