### ISSUE TITLE
Movement issue, stuck to the left side

### ISSUE THREAD

**Issue by CodingJhames** [mgba-emu/mgba#2970]
I'm using Ubuntu 20.04, so i tried to play Pokemon Emerald, once the game start i noticed the character start to walk to the left direction continuously, i don't have a controller connected i just used the keyboard, i tried to map the buttons so many times but that doesn't fixed the issue.

video recording from the issue:  [https://drive.google.com/file/d/1EOBkFY5YnKdLtQ9rkHrTFbc4XFfT2cfa/view?usp=sharing](url)
```[tasklist]
### Ubuntu 20.04 issue
```

**Comment by endrift** [comment]
This is either a bug with SDL or a bug with the kernel, not a bug with mGBA. This was best discussed on the discord or forums, as you did, instead of filing a bug, as it's not actually a bug in mGBA--it sees SDL says it has these game controllers attached, and it treats them as game controllers. The fact that something that's not a game controller is showing up is not something mGBA can reason about.
