### ISSUE TITLE
Phalanx: strange lines on clouds

### ISSUE THREAD

**Issue by detectorcaleta1** [mgba-emu/mgba#2982]
Hello, 

Every time you move the ship up and down, those strange lines appear on clouds, they also flicker, I don't know if the game had those glitches or if it's the emulator that is causing them, I don't have a GBA console to test it and either the game Phalanx. Those lines appear on all versions of this game, USA, EUR and JAP. Thank you in advance.

![1](https://github.com/mgba-emu/mgba/assets/49579368/3e5abfb3-d1a2-4457-8f63-ace5b95dcd16)
![2](https://github.com/mgba-emu/mgba/assets/49579368/d120c87f-c1dc-4ba6-96cc-75ba13fda099)

**Comment by ToniBC** [comment]
I have tried the game on a DS with a Flashcard and the result is the same. So those errors seem to be from the game. I would say that it is almost 99% certain that this is the case, that the game has those bugs.

It may be less noticeable on a GBA, due to screen ghosting, but right now I can't verify it.

Let's see if someone can verify it on a GBA.

**Comment by endrift** [comment]
Can confirm this happens on GBA too.
