### ISSUE TITLE
Dolphin integration lags tremendly over TCP

### ISSUE THREAD

**Issue by LuisMayo** [mgba-emu/mgba#3065]
Edit: Sorry I sent the issue by error

Anyway. The TCP connection doesn't work at all. In four swords adventure the game (both dolphin and MGBA) starts lagging a lot. I'm talking in the 1-2fps range. Rendering it unplayable

Which I find weird given that the integrated MGBA works perfectly

My setup included Windows as the Dolphin host and SteamOS3 (Arch Linux-like) as the MGBA client

**Comment by endrift** [comment]
The protocol is not designed to work well over the network due to timing constraints. The protocol itself was inherited from VBA, and I've been thinking about replacing it entirely instead (the new protocol being codenamed Orca). However, due to the presence of Integrated mGBA, this is extremely low priority.

**Comment by endrift** [comment]
Yes I know how weird it sounds that a networked protocol is not designed to work well over the network. I don't know why VBA designed it that way either.

**Comment by LuisMayo** [comment]
I figured so much since I've read a couple of times the problem about the network not working properly

Is there any GH Issue, blog or whatever I can keep and eye in possible Orca news? Even if it's low priority just to keep an eye of things

Thanks!

**Comment by endrift** [comment]
Not really, no. I sometimes blabber about what I'm working on on the Discord but that's about it.
