### ISSUE TITLE
mGBA missing options

### ISSUE THREAD

**Issue by BranwonX** [mgba-emu/mgba#3193]
mGBA is missing options when building with -DBUILD_LIBRETRO=ON, it is missing (Interframe Blending) and (Color Correction).

The forked core has the missing options, the above build does not have them.

Interfame Blending fixes the Ghosting issues with games like Golden Sun where in the overworld the screen pixles shake badly.

**Comment by endrift** [comment]
These options were intentionally not backported from downstream due to their implementation in the core instead of the frontend where they belong. If they were in the frontend they could be implemented in a way that was fast, such as shaders. However, Retroarch decided to implement them in a way that would be slow, especially on weaker systems.
