### ISSUE TITLE
mGBA Cheats wont work on Pokemon Fire REd

### ISSUE THREAD

**Issue by mamoreno11** [mgba-emu/mgba#320]
No matter how much I change the master codes and individuals pokemon codes, nothing happens...

I understand that I need to add a "+" between multiple spaces and yet it still doesnt work.

**Comment by endrift** [comment]
There are no plusses in codes. I really just need to write up a guide.

**Comment by mamoreno11** [comment]
That would greatly appreciated...

In this case I went ahead and clicked on the add cheat button..then I added the master code clicked enable now

Afterwards I went ahead and pasted the individual pokemon I wanted to catch and enabled that code as well

**Comment by endrift** [comment]
Can I see the site you used? A lot of them just have wrong info.

**Comment by mamoreno11** [comment]
http://pokemonfireredcheats.com/codebreaker-codes 

went to the "any pokemon you want"

Entered the master code:
000014D1 000A
1003dae6 0007

Then went ahead and added the level modifier and pokemon modifier based on the pokemon I wanted to catch...in this instance poliwhirl level 20

**Comment by endrift** [comment]
Try it without the master code. That sometimes actually *breaks* things in mGBA.

**Comment by mamoreno11** [comment]
nop didint work

**Comment by mamoreno11** [comment]
I have never had a problem in any other platform with cheats...its only been in this platform

**Comment by endrift** [comment]
The GBA is a shitshow of different code formats, some of which look similar, but all of which are mutually incomprehensible. It's trial and error to get them to work, really.

**Comment by mamoreno11** [comment]
it doesnt matter if its gameshark or action replay correct? the platform doesnt give you and option to choose

**Comment by endrift** [comment]
Those are all codebreaker codes. If you try to enter them as GameShark or Action Replay, they'll just get rejected.

**Comment by clobber** [comment]
@mamoreno11 Your codebreaker cheat will work under the following conditions only:

* Using mGBA 0.4.1
* Using ROM "Pokemon - FireRed Version (USA)" and **NOT** one labeled as **Revision 1/Revision A/Version 1.1**
* First enter the Master code
```
000014D1 000A
1003dae6 0007
```
* Then enter your modifier code
```
83007CEE 003D
```
* Ensure you entered the cheats separately and **NOT** grouped together, otherwise they will not work, e.g.

![screen shot 2016-08-22 at 1 34 05 pm](https://cloud.githubusercontent.com/assets/1303132/17866697/1f422ebc-686d-11e6-8ce9-9cf7826711c8.png)

Result:
![screen shot 2016-08-22 at 1 35 33 pm](https://cloud.githubusercontent.com/assets/1303132/17866744/53fcb74e-686d-11e6-99e4-c4e899ab01fa.png)

@endrift is correct in stating that "GBA is a shitshow of different code formats", especially with cheat code websites having codes mislabeled or plain wrong, without noting which region and revision they are.

**Comment by thesplitter** [comment]
Unfortunately this is not working, i have tried with mGBA 0.5.2 but when i try to add the master code
`000014D1 000A
1003dae6 0007`
the second line does not get saved, i have tried in many way, also manually adding it to the saved cheat file but nothing, when loading it the master code has just the first line :(

**Comment by endrift** [comment]
I think this might be fixed by now. Try in a newer dev build.

**Comment by clobber** [comment]
@thesplitter This type of cheat now works again as of commit https://github.com/mgba-emu/mgba/commit/1807b66bd60c4dadd91190833ca0a81e8d4d49bd, however @endrift has noted that there are currently other bugs where hooks may break codes in some games, and you can't disable master codes either, which is what contains the hooks.

**Comment by CrashyBang** [comment]
Hey @clobber, so just to be clear the current stable release will not be working? (Just having a nightmare of a time trying to get cheats to work).

Cheers,

**Comment by CrashyBang** [comment]
Update tried with 0.6.2 could not get that to work either, starting to think that I might be doing it wrong, using this guide https://fantasyanime.com/emuhelp/mgba#cheats
