### ISSUE TITLE
Linux 32-bit Version

### ISSUE THREAD

**Issue by sandboxgamedev123** [mgba-emu/mgba#3218]
A 32-bit AppImage was created for mGBA 0.10.3. This was tested on LMDE 6 Cinnamon 32-bit.

URL: https://github.com/sandboxgamedev123/Linux-mGBA-32-bit

### Checklist

The test systems:

 - [X] AMD Ryzen 5 5600H, NVIDIA GeForce RTX 3060 6 GB, 16 GB RAM, 1.5 TB NVMe SSD (in a VM using QEMU)
 - [X] Intel Core i5-7300HQ, NVIDIA GeForce GTX 1050 Ti 4 GB, 16 GB RAM, 512 GB SATA SSD (in a VM using QEMU)
 - [X] Intel Celeron M 360 1.4 GHz, Intel GMA 900 128 MB, 1.25 GB RAM, 160 GB 5400-RPM HDD

I am requesting a 32-bit AppImage to be added. Can I become a contributor to help in providing additional versions?

**Comment by endrift** [comment]
Sorry, I'm not going to add a 32-bit appimage to the builder. On Debian, one of the few distros that even still supports 32-bit x86, [popcon](https://popcon.debian.org/) shows that 32-bit represents only 3.7% of the userbase and shrinking. 64-bit x86 has 27 times as many users. I won't do anything to _break_ 32-bit support, but I don't think very many users will find it useful. The vast majority of Linux users are on 64-bit systems now.

**Comment by CasualPokePlayer** [comment]
The people who would be using 32 bit Windows and not 64 bit Windows would have 64 bit machines but did not use 64 bit Windows just due to memory constraints (64 bit Windows has a higher memory requirement than 32 bit Windows), or possibly just because the OEM was dumb. Linux does not have such a higher requirement. Actual 32 bit machines are definitely not being used here in any sort of significant capacity (the last 32 bit x86 CPUs would be 20 years old)

**Comment by sandboxgamedev123** [comment]
You made a good point regarding memory usage and why many people still use Windows 32-bit. But 32-bit machines are being used. I have one of them. I do not know what the number of people using 32-bit machines is.

**Comment by endrift** [comment]
The reason I ship 32-bit Windows builds is because they work without issue on both 32 and 64-bit Windows, and there's no real advantage to be gained from the 64-bit version. Sure, most people are using 64-bit Windows, but since this works equally well in both situations, I provide it. For a while I _didn't_ provide a 64-bit version separately, as there was nothing to be gained from it, but enough people asked that I gave them the placebo.

Linux is not as forgiving in all configurations, so while a 32-bit AppImage _might_ work on 64-bit Linux, this is not a guarantee. Most people are on 64-bit Linux and very few are on 32-bit. It is not worth the CPU time and storage costs of uploading another several megabytes per build for 32-bit AppImages in addition. It's already something close to long-term storage of 200 MB per commit. I have no interest in tacking on another 25 MB for a thing that single, maybe double digit users use. It's just too niche. Likewise, I plan to kill off the macOS "legacy" builds sometime after the next release.

**Comment by sandboxgamedev123** [comment]
I did not know you had costs for hosting the files.

The 32-bit Linux version would be for Linux 32-bit, while the 64-bit Linux version would be for Linux 64-bit. Other programs might be similar.

32-bit and 64-bit programs might be different for Linux but I think it is intuitive enough for people to download the version for their architecture.

In any case, what I am proposing for now is to add scripts for making 32-bit and 64-bit AppImage files.

https://github.com/mgba-emu/mgba/pull/3222
