### ISSUE TITLE
[Question] Un-reachable Library grid and icon view

### ISSUE THREAD

**Issue by chrisepstein** [mgba-emu/mgba#3238]
Hi endrift,

I love mGBA and I was going to see if I could add some features to the library view, like add/remove columns, re-ordering columns, etc. and I was wondering if it was on possible that the Grid and Icon library views didn't have reachable settings in the drop down. While making these changes in my fork if it's on purpose I wanted to clean up the un-used code, if it wasn't on purpose I wanted to add the settings etc.

Let me know and I'll get working on it, wanted to make sure I was going in the direction you wanted here?

**Comment by endrift** [comment]
Generally we don't accept questions on the issue tracker, only on the forums or the discord. In this case, the answer is simple enough: because we didn't have anything to *use as the icon*, so it would have been extremely plain looking.

That said, @ahigerd has been working on a big revamp on the library UI that's still pending and will hopefully be merged soon. You should try to coordinate with him on this.
