### ISSUE TITLE
Super Game Boy Border glitch

### ISSUE THREAD

**Issue by mitch03** [mgba-emu/mgba#3312]
Super Game Boy Border is glitched out, (i was playing pokemon yellow) to reproduce the problem load up a game and select super game boy border

**Comment by Squall-Leonhart** [comment]
is this another https://github.com/mgba-emu/mgba/issues/2832

**Comment by endrift** [comment]
Yeah I presume it is. Without more information I'm going to assume it's just "this is a GBC/SGB game running exclusively in GBC mode from the game's perspective", so it never sets the border. If it's just the vanilla version, that's definitely the case, but let me know otherwise.

I really do need to get around to implementing the hack version.
