### ISSUE TITLE
mGba Is NOT saving my games

### ISSUE THREAD

**Issue by 1Guss226** [mgba-emu/mgba#3377]
This emulator is terrible because it isn't saving the games (specially the pokemon games) that I spend hours playing and when I click to ''save'', I go back to play after relaxing and BOOM! All my games were restarted
![LIXO](https://github.com/user-attachments/assets/d08c34be-6f4a-48e9-9b70-71ae61d3dd4c)
Here, is my pokemon emerald restarted after I reached elite 4

**Comment by endrift** [comment]
Where are your ROMs located? If it's somewhere that mGBA can't write a save file to, like under Program Files, it gives you a warning. Lots of people just blindly dismiss those warnings without reading them though, leading to complaints like this.

**Comment by Catmansys** [comment]
> Where are your ROMs located? If it's somewhere that mGBA can't write a save file to, like under Program Files, it gives you a warning. Lots of people just blindly dismiss those warnings without reading them though, leading to complaints like this.

I don’t get now they got to elite four then decided to relax. That would take minimum of like 35 hours. Anyway on this subject of save file location, I was wondering if you could make a option to choose? On Wii it default save is games directory I got whole collection. So when I want to delete a save I use Wii explor but having to scroll through 950 files to find the save is annoying because Wii explorer doesn’t have search function and it chugs and takes time to load all them files to scroll through. Would be good if saves can be directed to (SD/mGBA/saves) it’s how other emulators on Wii store their saves. Can you please add this option? Setting could be called “save location” options could be “game location default) and “mGBA folder” or something like that. Thank you.

**Comment by endrift** [comment]
I can't help if you don't give me more info. If you do, I can reopen this.
