### ISSUE TITLE
Misbehaviour on THUMB-mode `bx pc` with non-word-aligned address

### ISSUE THREAD

**Issue by Aikku93** [mgba-emu/mgba#3382]
If `bx pc` is executed while the opcode isn't on a word-aligned boundary (ie. OpcodeAddress & 2 != 0), emulation goes wrong. I found this bug when reading a jump address and got a "rotated" 32bit value, as though reading from misaligned memory. [Minimal example](https://github.com/user-attachments/files/18221557/bxpc.zip): Real hardware switches the screen green (from DISPCNT = 0 and writing to BGPAL[0]), mGBA 0.10.4 stays white (not sure why; adding padding values around the read value doesn't help). Sorry about terseness - the page deleted the message I wrote after I uploaded the example, more than a bit annoyed at it.

**Comment by endrift** [comment]
What I'm seeing looks like pc-rel loads are acting misaligned, which we've already confirmed happens on hardware in some capacity. The load that attempts to move 0x3E0 into r1 in fact loads 0x03E00000 due to this. I'm pretty sure I confirmed this was the right behavior previously when I added support for misaligned PC jumps in the first place, so it's very strange that this seems to work on hardware. I wonder if it differs between RAM and ROM. See also #2964.

**Comment by Aikku93** [comment]
Huh, that's actually very weird (and I learned that doing `bx pc` from unaligned addresses is flaky). I tested on hardware once again, and you are right about the alignment thing. I really don't know why it worked for me when I last tested it, then, unless it's some "random chance" thing (in which case always emulating the misalignment is probably the right call).

I'll mark this issue as closed, then. Thanks.
