### ISSUE TITLE
[Wii] 240p Audio pop

### ISSUE THREAD

**Issue by Bizcocho** [mgba-emu/mgba#357]
Build: nightly-2016-08-22-wii-34db16b

Tested with Mother 3 and Minish Cap. You can hear it during the intro in Minish Cap for example.

0.4.1 doesn't seem to have this problem.

Update: It seems that 240p adds extra "pop" to the audio.

**Comment by ruijtunes** [comment]
I don't know if this is the way that you code de audio but maybe it can help:

Dborth changed de sample rate when in 240p mode:

// set VI mode and audio sample rate depending on if original mode is used

 	if (240p)
	{
UpdateSampleRate(48220);
SetSampleRate();
	}
 	else
	{
 		rmode = FindVideoMode();
		UpdateSampleRate(48000);
		SetSampleRate();
	}
 
 	SetupVideoMode(rmode); // reconfigure VI


And here is one ekeke post commenting this issue:

"It's because it's hard to have perfect sound AND video synchronization. 
Emulation on consoles is generally synced with Video Interrupt (VSYNC) which is approx. 1/50 
or 1/60s. In the mean time, audio is played through DMA at a given samplerate (32 
or 48khz). Both frequencies are however not *exactly* 60 frames/sec or 32000 
samples/sec on the Wii/Gamecube so desync happen after a while. The result in that case is 
that the previous audio DMA is played again, leading to sound lag once in a while.

A solution would be to synchronize emulation with audio DMA instead of Video
Interrupt but you will get similar frame skipping once in a while, though it's
generally less noticeable than sound skipping.

I've hard time figuring a perfect solution in Genesis Plus, it's not simple but 
the general idea is to have the output samplerate every frame (number of samples 
output per frames) match the exact framerate (I measured that on PAL60/NTSC, VSYNC 
occurs approx. every 16715 us which is approx. 802.32 samples per frames at 48kHz so 
you ned to ouput either 800 or 808 samples per frame to approximate this value)
"

**Comment by endrift** [comment]
I think this is fixed now. Let me know tomorrow when a new nightly is posted.

**Comment by Bizcocho** [comment]
Yes, the audio is cleaner now. Thanks!
