### ISSUE TITLE
Green Beret (PD) [C] black screen

### ISSUE THREAD

**Issue by benderscruffy** [mgba-emu/mgba#400]
using Mgba 0.5.0
nothing but a black screen

**Comment by endrift** [comment]
Fails in bgb as well. Is this known to work on hardware?

**Comment by benderscruffy** [comment]
who cares if it fails in bgb 
alot of things still fail to run properly in bgb
this does work on hardware

**Comment by endrift** [comment]
Sorry I asked a question that might have made it so I wouldn't have to break out my flash cart. I use bgb as a comparison, so if it's broken in bgb it's quite often broken on hardware too. And let me tell you, this ROM does weird shit right off the bat. It looks highly likely to me that it will be broken on hardware too. That's why I asked.

So I care if it fails in bgb. If you don't, then don't be an ass about it.

**Comment by endrift** [comment]
Figured out why it "works" on hardware and I think it might be an issue with the flashcart I have. The game requires SRAM to be writable by default, which, afaik, MBC5 isn't.

**Comment by MoochMcGee** [comment]
@benderscruffy One, that's kind of known to not be true. Secondly, bgb is basically THE most accurate DMG emulator out there, barring gambatte which is close.

**Comment by benderscruffy** [comment]
that is funny : )

**Comment by MoochMcGee** [comment]
Um, how is that funny? I mean, I know I'm often rude, but holy shit, at least I've got logic and facts to back me up. This is just rude for the sake of it.

**Comment by endrift** [comment]
I did some research a while back, and this would fail on hardware if the hardware has a proper MBC5.
