### ISSUE TITLE
GB/GBC video layer toggles don't work

### ISSUE THREAD

**Issue by Jaffacakelover** [mgba-emu/mgba#434]
Background 0/1/2/3 and OBJ (sprites) can be toggled on/off individually when running Game Boy Advance roms, using either the menu options or the shortcut keys. The menu options and shortcuts do nothing when running any Game Boy or Game Boy Color rom.
Toggling Audio Channels works with both GBA and GB/GBC roms.

**Comment by endrift** [comment]
These don't do anything on GB/GBC because the GB notion of graphics rendering is completely different than the GBA's. The GBA has a backdrop, four background layers and a sprite layer, whereas the GB/C has one background "layer" (no backdrop), the window, and sprites. I could make it so you can disable the window and sprites, or possibly simulate a backdrop, but I'm not sure it would actually be useful at that point.

**Comment by endrift** [comment]
*nod* that sounds reasonable. I'll see what I can do.

**Comment by endrift** [comment]
Fixed in 189169e8ec2ca526f6e07308464ff079dd1f56b2.
