### ISSUE TITLE
[Request] D-Pad Support for XInput/DirectInput hat switches on gamepads/controllers

### ISSUE THREAD

**Issue by Lv44EnderShaman** [mgba-emu/mgba#452]
Build: 0.5.1-master-c4dbe0a
OS: Windows 7 Home Edition 64-bit
Replicated with: Logitech Gamepad F310 (detected as Logitech Dual Action)

While the button mapping feature of the emulator supports gamepads' analog sticks as valid inputs for the in-game directional-pad, it is this user's notice that the emulator does not support mapping the Logitech F310's directional-pad as valid button inputs. This was replicated in both the gamepad's XInput and DirectInput modes. It is my theory that the gamepad maps its directional pad as the equivalent of hat switch signals, which mGBA to this date has had no sign of detecting for directional pad input. It may be a simple enough fix, if possible: Just add detection for hat switches from both XInput and DirectInput gamepads.

**Comment by endrift** [comment]
1. Hats do work, they just aren't remappable. Up = Up, Left = Left, Right = Right, Down = Down. This is currently hardcoded.
2. It's not a simple fix, as they show up completely separate from axes and buttons, so I'd need to add an entire new codepath through the controller codebase, which isn't exactly the simplest thing.

**Comment by endrift** [comment]
...it looks like I removed hat support pending a rewrite and then forgot to put it back. I should do that.

**Comment by Nicholas-Steel** [comment]
Yep, can confirm HAT support is missing. Thankfully the Logitech F310, F510 and F710 have a button that will swap the analog stick functionality with the DPad functionality.

**Comment by CharlesCorrin** [comment]
Strange. I'm using the latest test build and my DPad works. I'm using the Logitech F310 as well and have "mode" turned off. :S

**Comment by Nicholas-Steel** [comment]
Windows 10 has nothing to do with it, read my response in the other report.

**Comment by CharlesCorrin** [comment]
Is it an old version? Because I've confirmed that the last five development builds (from the 11th to the 21st in January) all have working DPads on the Logitech F310 without using the mode button.

**Comment by Nicholas-Steel** [comment]
Did you not read this bug report topic? It doesn't work in v0.5.1 and Endrift has made it clear it also does not work in v0.5.2. Endrift has also made it clear that it will be re-implemented at some point between v0.5.2 and v0.6.0 and you have confirmed this.

Go back to v0.5.2 to see for yourself that support was missing. I don't know why you would want to do this when the developer has already stated that the support was removed and never re-implemented though.

**Comment by endrift** [comment]
Regardless, it's back now. See f4a61f91d46b8a90a61ca0f9ef04f431f0a4fd9f.

**Comment by CharlesCorrin** [comment]
I'm sorry. I didn't mean to offend you. But I did check for myself and the DPad did work in the test builds on my machine. I made no error on that. I don't get why you felt it necessary to insult me over it when I've only been honest.

Because you're so sure, I tested your cited v0.5.2 for myself. My DPad works in it both with and without the mode button activated. I can't explain to you why it does, but it does.

Regardless, it's good that whatever broken thing existed was fixed, though it never affected my controller for some reason. Perhaps endrift has some explanation for this over why one person would be affected but not another? It could be useful for people to better test things in the future.

**Comment by Nicholas-Steel** [comment]
I was just saying it was a bit ingenuous to claim the problem doesn't exist when testing a Test Build that was made after the version that the bug was reported for, because the problem is likely already fixed. In your case though it's likely the problem only cropped up in the Windows version of the program which would explain why you don't notice it in v0.5.2 either.

**Comment by CharlesCorrin** [comment]
On the contrary: I was pointing out a discrepancy between my observation and another's. I don't see how pointing out my own observation is naive when it can be useful to check for differences between systems to find potential issues.

And alas: I just tested using a completely fresh config file and v0.5.1 still has working DPad for me. I also only use the Windows version. So the mystery of why it always works for me continues. :S

**Comment by Nicholas-Steel** [comment]
CharlesCorrin, can you confirm that switching between XInput and DirectInput actually switches the device that Windows sees the gamepad as? For me Windows is prone to continue thinking the device didn't change when I flick the switch (I have to physically unplug it and plug it back in for Windows to see it as a different device, though lately this is less of an issue? Maybe a Windows Update improved the behaviour).

Flicking the switch should change the device between these 2 names in Windows Control Panel > Devices & Printers:

Logitech Dual Action
Logitech F310

**Comment by CharlesCorrin** [comment]
Hey again. :3

When I flip the switch, it changes. In x input, it has these:

HID-compliant game controller
USB Input Device

In direct input, it has these:

Logitech Dual Action (HID)
Logitech Dual Action USB

No "F310" in the device manager even though the controller's sticker identifies it as an F310. As an aside, I once had the official software for the controller, but I uninstalled it. I never installed it again because I haven't needed it. I assume that somewhere, in the computer, something weird is going on.

Ironically, since the POV HAT update, I need to actually configure the DPad now to make the controller behave. It no longer works well with the default settings. XD

**Comment by endrift** [comment]
Er, hm, I'll need to look into that later.

**Comment by Nicholas-Steel** [comment]
"Devices & Printers" is not "Device Manager". Both are however located in Control Panel. However the switch seems to be working fine on your PC.

**Comment by CharlesCorrin** [comment]
Oh, yes... My mistake. Sorry. : / I nearly never go into Devices & Printers... Anyway, on the Devices & Printers screen, it says "Gamepad F310" in both xinput and directinput. That's probably because I don't have the software installed for the direct input. Steam and a few emulators automatically recognize the controller as xinput anyway.

Because endrift says she'll "look into that later", I'll take a moment to be more specific about the POV Hat thing I mentioned earlier: Currently (build 369592d), the default POV Hat settings will make my (admittedly odd) controller think several buttons are assigned to the GBA DPad in addition to the controller's DPad. For example, the F310's B button (the red one) will activate a press of "down" on the GBA's DPad. It isn't really a big deal (I think?), because you can just configure the controls, but mileage could vary, I suppose.

**Comment by Nicholas-Steel** [comment]
Yeah, so if the gamepad is currently detected as a Logitech F310 than you should:

1) Unplug the gamepad.
2) Flick the switch to Direct Input.
3) Plug the gamepad back in to the computer.
4) It should now appear as a "Logitech Dual Action" device in Devices & Printers.

If it remains being listed as Logitech F310 than Windows has failed to switch the drivers for the device and is continuing to use the XInput drivers.
