### ISSUE TITLE
Wii U VC GBA support

### ISSUE THREAD

**Issue by Hking0036** [mgba-emu/mgba#471]
I mentioned this briefly in my previous issue but I figured I'd make another just to give it it's own issue.

Wii U has GBA VC, and when you dump roms from the VC a lot of times you find that they've actually patched a number of the roms they've put in. Most of these are completely undocumented, presumably most are just rapid flashing fixes, others have some interesting stuff like the well-acknowledged SMA4/SMB3 rom. A few seem to rely on wii u emulator functions however, and fail to boot on any emulator, Most fail to boot on a real GBA either. I don't know how feasible this is to implement or if it's even interesting but I figured I'd bring them to attention so you can look at them if you want to:

Roms that fail to boot:

- Mega Man Battle Network 5: Team Colonel/Team Protoman (White screen on boot, another patch exists to allow it to run, illegal opcode 0000e825)
- Final Fight One (Black screen after Capcom screen, illegal opcode: 0000e801)
- Super Street Fighter II Turbo Revival (Black screen after Capcom screen, illegal opcode: 0000e808)

Mega Man patches can be found [here](http://forums.therockmanexezone.com/topic/8947437/1/)

and Final Fight One/SSF2TR patches can be found on my personal spreadsheet: [here](https://docs.google.com/spreadsheets/d/14kuiSrAL3GGvux93lYf3TRv4i309qeZFDt0weMh34o8/edit#gid=0) or in a folder [here](https://drive.google.com/open?id=0B09ZqzABOnZTYVlSbnRyLXptN2c).

**Comment by endrift** [comment]
I'll take a look at some point but because they fail to boot on a real GBA, this isn't high priority and may not get fixed.

**Comment by Hking0036** [comment]
I understand, they're just a neat anomaly and I figured you might want to look at them.

**Comment by Hking0036** [comment]
Sorry to give you bad info, but I tried again and Street Fighter II Turbo Revival loaded fine on my GBA this time, my everdrive gave me a FAT Error the first time but after re-copying it it loads up. Final Fight one stops at the same spot as it does in MGBA, and Battle Nets all stick on the white screen at the start but SSF2TR loads up fine and plays games fine.

**Comment by endrift** [comment]
The Battle Nets are all hitting an invalid instruction. I wonder if they trap into the Wii U's GBA emulator to do HLE or something.

**Comment by Hking0036** [comment]
Presumably, comparing apples to oranges here but most snes games come with pcm music packs separately from the rom presumably for HLEing as well.

**Comment by Prof9** [comment]
I've looked at this issue for MMBN5 [before](https://gbatemp.net/threads/does-anyone-have-an-ips-patch-of-the-wii-u-version-of-mmbn5.418667/#post-6176538) and what I found is that this opcode controls **frame blending**. Specifically, for MMBN5, it executes opcode 0xE825 with r4 = 0 and r5 = 0 or 1 to disable/enable 2-frame blending based on whether you're in a specific area.

I actually didn't know Final Fight and Street Fighter had the same problem so I just took a quick look at them too. It looks like they also get frame blending in the VC versions for specific scenes, for example in the intro:

![http://i.imgur.com/ejsSCtY.gif](http://i.imgur.com/ejsSCtY.gif)
(Left/right frames from GBA, blended frame from Wii U; note that Wii U colors are darker.)

Similarly, Street Fighter enables blending during character selection to make the background animation appear smoother (though curiously it disables it during Normal/Turbo selection), and at the start and end of every match (when the announcer text is rapidly blinking). Final Fight uses blending during the intro to make the rapidly flashing text box background appear a constant (semi-transparent) color.

From looking at these instructions in a disassembly I think I've figured out how they work, at least partially. Here is a comparison of the instructions used in the three games, whether they toggled blending on/off and which registers were used by it (and which values they contained).

```
E800    1110100000000000    off           r0=0,r0=0
E801    1110100000000001    on            r0=0,r1=1
E808    1110100000001000    on            r1=0,r0=1
E809    1110100000001001    off           r1=0,r1=0
E825    1110100000100101    on/off        r4=0,r5=X
                  XXX       register A
                     XXX    register B
```
This is by no means a confirmation of course but I think it's enough of a correlation that it's safe to say the lowest 6 bits control which 2 registers the opcode uses, and that register B controls the on/off setting for frame blending.

It would be nice if more games were found that used this mechanism; maybe there are other emulator functions that the VC ROM can control. **As for mGBA**, since it doesn't have frame blending, maybe it could just skip these opcodes by masking with 0xFFC0 and checking that register A contains 0? That way if any future ROMs crash, we know for sure that it uses an as-of-yet unknown emulator function.

**Comment by endrift** [comment]
Yeah, this is basically a more detailed version of my analysis on the issue. It SHOULD be possible to skip that opcode, but I'm not sure if I should whitelist the ROMs that use it or just allow it in general. The former is, well, you know. A game specific hack. But the latter is in theory compatibility-breaking. However, since if a game hits an unknown opcode on hardware, it just crashes (always), this might be an acceptable solution.

**Comment by Prof9** [comment]
Perhaps an option in the settings -- Wii U Virtual Console compatibility mode?

**Comment by endrift** [comment]
I tested skipping the opcode and that lets MMBN5 boot and run normally. I think I'll commit that because it really won't break anything except games that crash under normal conditions (which aren't really desirable anyway)

**Comment by FishamanP** [comment]
Doing so will introduce inaccuracies with ACE exploits. I see the value in both having and not having the opcode handled, so I would prefer a switch on stuff like this.

**Comment by endrift** [comment]
How would it introduce inaccuracies with ACE exploits? When you execute an illegal opcode, the CPU enters UNDEFINED mode, which, thanks to the GBA BIOS, cannot be used in any meaningful way. It tries to jump into DACS, which does not exist on retail games, so it...just hardlocks.

**Comment by Sanqui** [comment]
I believe the inaccuracy is in the opcode being ignored.  On Game Boy, for example, when the emulator _ignores_ an invalid opcode instead of hardlocking on it, more exploits are possible - and it's annoying to find out they don't actually work on hardware later.

**Comment by endrift** [comment]
The GBA has far more undefined opcodes than the GB does, so it's extremely unlikely for that to be the ONLY one. But regardless, mGBA *does* log when you hit that opcode, so you can see it.

**Comment by FishamanP** [comment]
Logging is close enough, I guess.
