### ISSUE TITLE
Feature request: Load patch which has the same filename with booted rom automatically

### ISSUE THREAD

**Issue by CarterLi** [mgba-emu/mgba#51]
An option in settings to enable / disable this feature is preferred

**Comment by tony971** [comment]
Is loading an un-patched ROM with a separate IPS a thing? I thought patches had to be applied to the ROM.

**Comment by endrift** [comment]
Tentatively putting in 0.4.0. I might get to it in 0.3.0, but it's not a hugely important feature.

**Comment by endrift** [comment]
Added in 071fe7ff2dc0a7cc396408f6558b4ad2d430a909.

**Comment by Sagiri** [comment]
Is there really not a way to disable this?

Currently, I have it set to look for patches in a read-only folder without any patches in it, because that seems to be the only way.

**Comment by zeromus** [comment]
Typically one does not even get patches with the same name as the booted rom without renaming `Cool Game (patch that does XYZ edition).ips` to `Cool Game.ips` alongside `Cool Game.rom`, so most people's workaround is to never do that in the first place unless they want to run a patch. 

Loading game.ips, along with game.sav and game.cheats and game.this and game.that without any provision for altering that is behaviour from the most ancient of times. So don't act so shocked.

**Comment by endrift** [comment]
I don't see the problem. Why would you be naming your patches the same as your ROM if you didn't want it to autoload?

**Comment by zeromus** [comment]
Believe it or not, 99% of the time people have a rom the same name as a patch, they're expecting the patch to be automatically applied; because that's how it works most of the time. Typically the patch file would have a version number in it, and (I think--I dont do things this way myself, but fact is, most people must or else this feature would not be so universally adopted) you would copy the rom to have a name that matches the patch, and let the patch get applied automatically. 

There are theoretical advantages to doing it this way. The emulator could check the rom against its database unpatched, make intelligent decisions, and then apply the patch. If you patch it yourself, it couldn't do that.

This also improves the workflow for the people building the patch, for whatever that's worth.

Yeah, automagic is often confusing. It's simple until it isn't.

Patches are more generally applied to disc images manually, though. I don't see why we can't force everyone to automatically apply patches, but that ship has sailed long ago.
