### ISSUE TITLE
Shift key not displayed correctly in Keyboard settings

### ISSUE THREAD

**Issue by Prof9** [mgba-emu/mgba#525]
See image below, where Right Shift has been assigned to the Select button. It shows up as garbage in the settings, but it _does_ work correctly in-game (as well as Left Shift). Using the latest nightly (17cfee0) on Windows 10 x64.

![http://i.imgur.com/pbcmQaX.png](http://i.imgur.com/pbcmQaX.png)

**Comment by endrift** [comment]
I'm under the impression that this is a Qt bug. I've seen it before.

**Comment by obskyr** [comment]
Can confirm! Interestingly enough, if you press shift together with another key (or within a short timeframe after pressing another key), it shows up just fine. Here I've juggled the interface enough to set Select to shift + left mouse (which just displays as `Shift+`), and Start to shift + M.

![Settings](https://cloud.githubusercontent.com/assets/4363779/26264201/3b6e93ac-3cdc-11e7-8946-99f0084053c2.png)

Incidentally, it turns out entering key combinations is possible although incredibly (*incredibly*) finicky.

**Comment by endrift** [comment]
For what it's worth, this entire interface is getting replaced when the [input revamp](https://github.com/mgba-emu/mgba/projects/3) is done. An early version of it was merged into medusa but it's...rather early still and buggy. It will probably need a full redesign, even.

**Comment by endrift** [comment]
Turns out this is a bug in Qt itself. I'll have to work around it.
