### ISSUE TITLE
GBA Sleep Mode doesn't work

### ISSUE THREAD

**Issue by sergiobenrocha2** [mgba-emu/mgba#584]
There's a sleep feature in Drill Dozer, I remember it was working sometime ago. Tested in 0.5.2 + few commits, libretro, android. Same issue with or without bios

Select the sleep, the screen will flash and it will go back to the game

![drill dozer usa -170409-024927](https://cloud.githubusercontent.com/assets/5431285/24835144/34c772a8-1ccf-11e7-800d-9740774f4219.png)

**Comment by sergiobenrocha2** [comment]
Same issue with Metroid Fusion

**Comment by endrift** [comment]
It's not a bug, *per se*. Sleep mode is a way to turn off the hardware, save for the RAM, and bring it back on later. mGBA supports using a callback to tell the frontend that a game is about to go to sleep. But, no frontend does anything with this (at the moment; the GBA core supports it but the GB doesn't, so the Qt frontend used to support it, but it hasn't been put back since introducing the GB core). As such, the game just wakes up immediately, resulting in no perceptible change. I should put this back, though.

**Comment by endrift** [comment]
Restored in 484618ca4c5f59f62a73018051ca6397472ea35e, but it's still pretty confusing to use.

**Comment by sergiobenrocha2** [comment]
Actually I was referring to the libretro port, or this was feature never a thing there?

**Comment by endrift** [comment]
It was never implemented there, nor do I know what to do with it there.

**Comment by sergiobenrocha2** [comment]
Is it possible to change the cartridge in the real system? I was expecting a blank screen in Qt, and with L+R+Select I could return; instead, it just shutdown the emulation.

**Comment by endrift** [comment]
No, if you pull out the cartridge, it wakes up and crashes.

Also, once you reload the ROM it'll be right where it left off. But yeah that's why I said it's confusing.

**Comment by sergiobenrocha2** [comment]
Yeah, I tested with Metroid Fusion:

![metroid fusion usa australia -0](https://cloud.githubusercontent.com/assets/5431285/24883156/1c7281d8-1e1a-11e7-996a-298a7cc24bc7.png)

I'm not sure if it's there it re-start in the real hardware

**Comment by RafaelOliveira71594** [comment]
Having The Same Issue After The Update
