### ISSUE TITLE
MOTHER 3: Timing Issues

### ISSUE THREAD

**Issue by DragonDePlatino** [mgba-emu/mgba#822]
The rhythm battle system of MOTHER 3 does not work because of synchronization problems between audio and player input. That, or small fluctuations in framerate are throwing off the timing. Here's some footage of the problem:

[MOTHER 3: Emulator Timing Woes ](https://www.youtube.com/watch?v=9MzaaBcxusI)
(More information in the description)

If you want to replicate this issue, battery saves of the game can be downloaded [here](https://forum.starmen.net/forum/Games/Mother3/Mother-3-Froggie-Battery-Saves-Library/page/1/). Choose the last save file then access the Battle Memory (yellow book) in your Key Items.

**Comment by endrift** [comment]
Have you been able to reproduce this on hardware? You'll need a flashcart to install the English patch of course.

**Comment by DragonDePlatino** [comment]
Sorry, I don't have a flashcart. From what I understand, this is a widely-known issue that [many people](https://forum.starmen.net/forum/Games/Mother3/Tips-on-Rhythm-Combos/first) have been able to replicate.

Flash carts work fine but a GBA emulator accurate enough to emulate the rhythm battle system has never been made. I've tried this in 3-4 different emulators and none of them work.

**Comment by zeromus** [comment]
Computers are complicated. Audio latency, video latency, input latency. Gamepad latency, USB latency. GPU "optimizations" adding even more video latency. Nothing the emulator can even do anything about. It's often not even worth trying to do anything about it because it will be whackamole, making things better on some systems and worse on others. But never perfect. Anyone who wants perfectly synchronized emulation needs to begin by building a specialized system.

**Comment by endrift** [comment]
A "widely-known issue" in emulators that aren't mGBA apparently--that thread hasn't seen a post in longer than mGBA has been a thing.

I was typing up a big thing about how latency is a thing but then zeromus beat me to it.

**Comment by DragonDePlatino** [comment]
Emulators have gotten a lot better since 2008, yes. But I have been able to reproduce this in emulators as recent as VBA-M. I understand latency is an issue but can we not have more options to get it as good as possible on that user's particular hardware? I've revisited this game several times over the years and always wanted to find an emulator that could play it properly. :(

**Comment by zeromus** [comment]
No, because it's whackamole. "As good as possible" is in many ways a moving target.

Many people find many games which arent even rhythm based to be unplayable on computers. "Do everything possible to reduce latency" is always an implied task for every emulator frontend, with priority varying depend on the frontend author's interests. It's not to fix a bug, it's a general quality of life issue.

Using words like "properly" to imply that an impropriety is happening rather than a choice to dedicate creative resources to other more attainable enhancements is a great way to annoy people.

**Comment by DragonDePlatino** [comment]
Okay, I understand. This is an amorphous issue with a single feature in a particular game and there are higher priorities in mGBA's development. I won't press the issue any further.
