### ISSUE TITLE
UI Cleanup

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#83]
Some options really don't need shown. The UI can be made simpler without them.

- [x] "Audio driver" in Windows (but could be kept around/commented out if Qt multimedia is going to be fixed up eventually)
- [ ] "Enable rewind" - a rewind history of 0 states is functionally the same.
- [ ] "Skip BIOS intro" can be grayed out if "Use BIOS file" is unchecked. If you decide to make this change, perhaps the order of the two options should be switched.
- [x] "Exit fullscreen" in shortcut editor. Keeping the escape key as a fullscreen escape option is standard. There's no reason people would change it. Plus, it looks weird since "Toggle fullscreen" already exists.
- [ ] "Step backwards" could dynamically commandeer the rewind and/or held rewind buttons while emulation is paused. (Originally requested as part of #61 - closing that issue and breaking it apart)

**Comment by cascardian** [comment]
To add to this, here are some more Qt UI bugs (I'm running Windows 10) with the latest dev build:

- [ ] The *Fast forward speed* option as well as the *FPS target* option do not stick after opening the *Settings* window under *Tools* when the dialog is closed with 'OK' and no settings are changed. Fast forward speed gets reset to *Unbounded* every time, too (while not showing the 'selected' mark under *Emulation*).
- [ ] Moreover, the FPS target changes from the native 59.7275 setting (as per config.ini) to 59**,**73. It also seems that the comma--instead of a period--messes with mGBA's recognition of the option and the game speed suddenly increases as if **no** frame limit were present; the games I tested started fluctuating wildly between 500 and 700 FPS. Reopening the settings dialog again while in ludicrous speed reveals the setting to be changed to 0,01. The *Settings* window also accepts only a comma and no period as input. Therefore, if one wished to set a completely custom FPS target, it'd have to be done via the config.ini.
- [ ] Under *Game Pak sensors*, the *Tilt sensor* options also show commas instead of periods. This whole commas/periods thing needs to be cleaned up.
- [ ] The correct *Frame size* setting is retained but does not show the 'selected' mark upon restarting mGBA.
- [ ] When *Skip BIOS intro* is checked, *Boot BIOS* makes mGBA crash instantly. Thus, *Boot BIOS* should either be greyed out when this is set, or it should still be able to, well, boot the BIOS.

That's all I have for now. Thanks for your hard work, endrift!

**Comment by endrift** [comment]
- I have no intention of removing the audio driver pulldown on Windows. It would be a huge pain to make it system specific, especially since I'm planning on adding new ones in 0.4
- I'm not removing the ability to change the exit fullscreen hotkey. What if someone wants to unmap it?
- Almost all of @cascardian's issues are locale bugs that I don't really have any good way to test. I thought I'd worked them out when I added ftostr_u, but clearly not. If your locale uses commas instead of fullstops, shit will break I guess. If it uses fullstops, your first three issues all go away.

As for the other ones, thanks for piling them on me right before I release 0.3.0 instead of several weeks beforehand. Good thing to wake up to.

**Comment by tony971** [comment]
There isn't any rush on these. They're all aesthetic. You could tag them for the 0.9 release if you wanted. There's no functional difference. But sorry, I could have reported these as I thought of them.

**Comment by endrift** [comment]
Moreover, it's good to separate logically distinct items as separate bugs instead of clumping them into meta-bugs like this.

Also I hope I don't do an 0.9, I want to release 1.0 after 0.5 or 0.6 :(

**Comment by tony971** [comment]
Should I separate the three remaining ones, then?

**Comment by cascardian** [comment]
Locale bug confirmed. If anyone else wants to test this, you don't have to change your entire locale in Windows via *Control Panel -> Region -> Format*. Simply click *Additional settings...* and change your decimal symbol to a full stop to fix these issues.

I am sorry for piling these onto you and not separating properly. To reiterate for everybody reading, the settings check mark stuff is separate from the locale stuff, and I will separate these into their own issues if you wish so, endrift.

If there is any way to further help with testing, I'd be happy to.

**Comment by endrift** [comment]
I've just (hopefully) fixed the locale issue (seems to work fine now on Linux), and the boot/skip BIOS issue. I've confirmed the checkbox for frame size issue (it works on OS X fine!) so I'm gonna poke at that quickly. The rest of @tony971's stuff won't get fixed for 0.3.0 (maybe in 0.3.1), so those should probably be broken out into separate issues.

**Comment by tony971** [comment]
All remaining requests have been split into their own issues.
