### ISSUE TITLE
[feature request] GBC colorization for GB games

### ISSUE THREAD

**Issue by tony971** [mgba-emu/mgba#833]
This feature, implemented in Gambatte, allows some GB games to "colorize" while emulating them being played in a GBC/GBA. Pokemon Red/Blue/Yellow are probably the most notable games that take advantage of this feature.

**Comment by vaguerant** [comment]
Minor correction: the international version of Pokémon Yellow is actually just a full-blown GBC game, it's not using the custom palettes for monochrome games that the GBC provides. I know the box says "Game Boy", not Color, but the ROM says otherwise. The Japanese release, however, is a true DMG game.

**Comment by endrift** [comment]
Pokémon Yellow JP is an SGB game, and Red/Blue might be too.

**Comment by magical** [comment]
They are, yes.

**Comment by endrift** [comment]
Added, finally.
