### ISSUE TITLE
WarioWare GSF won't boot

### ISSUE THREAD

**Issue by kode54** [mgba-emu/mgba#865]
Here's a ROM converted from one of the MINIGSFs. It doesn't produce any audio, so it's hanging up somewhere.

https://f.losno.co/warioware_gsf.zip

**Comment by vaguerant** [comment]
This ROM, modified to add the Nintendo header and fix the checksum, initially works on hardware (Nintendo DS Lite) but seems to have some odd behavior around saving. Presumably it doesn't expect to save at all, but my flash card solution auto-writes a blank save file for any game flashed (I believe filled with 0x00), and this ROM seems to populate it with some (junk?) data. A copy of the save after running the ROM is attached below.

[warioware_gsf_sav.zip](https://github.com/mgba-emu/mgba/files/1309814/warioware_gsf_sav.zip)

On hardware, the ROM runs fine on first boot, but locks up after the Game Boy/Nintendo logo on any subsequent boot until the save data is cleared.

mGBA similarly auto-creates saves, and fills them with 0xFF ... I tried using the overrides system to set the save type to NONE rather than autodetect, but the result was no different; it still locks up as in the original report.

Still, given the issues I had with saving on hardware, I can't help wondering if it's related to the reason the ROM locks up on mGBA. From an end-user perspective, the result of subsequent booting with the malformed save looks identical to booting on mGBA: namely, the GBA BIOS logo and then a blank white screen forever.

**Comment by kode54** [comment]
Looks like these need the same fix that I applied to the Mario & Luigi GSFLIB. That also had a save initialization routine that was left in the boot up process, which, upon removal, the GSF set boots properly in mGBA.
