### ISSUE TITLE
Saving issues with mgba core

### ISSUE THREAD

**Issue by Mario418** [mgba-emu/mgba#931]
Im using mgba with retroarch, saving works well at first but if i shutdown my machine, all the saves will be gone when trying to load them

**Comment by endrift** [comment]
Sounds like an issue with Retroarch, not mgba.

**Comment by OptimalJew** [comment]
It's a Retroarch thing.

With Retroarch, unless 'SaveRAM Autosave Interval' is enabled, Retroarch writes SRAM on exit, and this goes for all cores, not just mGBA. The problem is that if you don't gracefully exit, your SRAM won't be written, and then the next time you load it up, your save will me missing.  It's disabled by default, as it doesn't play nice with how certain games use the SRAM.
