### ISSUE TITLE
The game "Anguna" fails to run in mGBA

### ISSUE THREAD

**Issue by FreeFull** [mgba-emu/mgba#96]
Anguna is a free indie GBA game available here: http://www.tolberts.net/anguna/
The game works in other emulators, I'm not sure if it works on real hardware or not as well.
In mGBA (commit cad90d1768), only a blank white screen shows. mGBA does work perfectly with other ROM files, this is the only one I've encountered an issue with so far.

**Comment by endrift** [comment]
Strange, this game works in GBA.js and has (I believe) historically worked in mGBA as well. Let me try bisecting.

**Comment by endrift** [comment]
It works with the official BIOS on latest. This is a bug in the HLE BIOS.

**Comment by endrift** [comment]
This is actually a timing bug/programming error in the homebrew. It doesn't mask vblank interrupts while setting up, and it gets a vblank interrupt before it's done setting up, leading to it being very confused.

**Comment by endrift** [comment]
Should be fixed in e9d4219d7b691e01df9f50b128f6de56fa82d57a.

**Comment by FreeFull** [comment]
Thanks for the fix. I don't believe the GBA version is being developed any more, so I'm not sure I should notify the author of the game about the bug.

**Comment by endrift** [comment]
Well it doesn't reproduce on hardware so I'm sure it'd be pretty low priority to fix. *shrug*

**Comment by gauauu** [comment]
Anguna developer here. 

Interesting stuff... The game worked in all the emulators and hardware I tried, so I never discovered this bug.  (We just released a semi-commercial version so I wish I had seen this earlier)

That being said, I'll take a look, but I'm not sure whether I'll bother to go back and fix it. Either way, I appreciate knowing that the bug is there!
